// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "sandboxed_api/tools/clang_generator/codegen.h"

#include <algorithm>
#include <cstddef>
#include <memory>
#include <optional>
#include <string>
#include <type_traits>
#include <variant>
#include <vector>

#include "absl/container/flat_hash_set.h"
#include "absl/functional/overload.h"
#include "absl/log/check.h"
#include "absl/log/log.h"
#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "absl/strings/ascii.h"
#include "absl/strings/match.h"
#include "absl/strings/str_cat.h"
#include "absl/strings/str_format.h"
#include "absl/strings/str_join.h"
#include "absl/strings/string_view.h"
#include "absl/strings/substitute.h"
#include "absl/types/span.h"
#include "sandboxed_api/tools/clang_generator/annotations.h"
#include "sandboxed_api/tools/clang_generator/emitter_base.h"
#include "sandboxed_api/tools/clang_generator/generator.h"
#include "sandboxed_api/tools/clang_generator/ir.h"

namespace sapi {
namespace {

constexpr absl::string_view kIncludePrefix = "";

// Evaluates to true if T is identical to any of the types in Allowed.
//
// DESIGN NOTE: In visitor patterns over sum types (std::variant), using an
// unconstrained fallback like `[&](const auto&)` can silently swallow new
// variant types introduced in the future, converting what should be a
// compile-time error into a runtime bug.
//
// While C++20 concepts could be defined for fallback whitelists, every
// std::visit in this file partitions parameter types slightly differently
// (e.g., EmitFuncDecl has a different default set than EmitWrapperDecl or
// Sandboxee argument passing), which would lead to an explosion of single-use
// concepts.
//
// Instead, we use `static_assert(IsOneOf<T, ...>, "...")` locally within each
// generic fallback lambda. This guarantees:
// 1. When a new parameter payload is added to ParameterPayload, the build
//    breaks independently at EVERY call site that doesn't explicitly handle it.
// 2. The author is forced to audit each block and make a conscious design
//    decision for that specific code generation phase, flushing out bugs.
// 3. We avoid duplicating boilerplate logic across 6+ variant types.
//
// Example:
//   std::visit(
//       absl::Overload{
//           [&](const ir::CallbackParam& cb) { ... },
//           [&](const auto& p) {
//             using T = std::decay_t<decltype(p)>;
//             static_assert(
//                 IsOneOf<T, ir::VoidParam, ir::ScalarParam, ir::BufferParam,
//                         ir::OpaquePointerParam, ir::StructSyncParam>,
//                 "Unhandled parameter payload type in EmitWrapperDecl!");
//             absl::StrAppend(&out, param.type.canonical_name, " ",
//             param.name);
//           },
//       },
//       param.payload);
template <typename T, typename... Allowed>
inline constexpr bool IsOneOf = (std::is_same_v<T, Allowed> || ...);

constexpr absl::string_view kWrapperPrefix = "sapi_wrapper_";

constexpr absl::string_view kCommonHeader =
    R"(// Automatically generated by SAPI interface generator; DO NOT EDIT.

// NOLINTBEGIN(whitespace/line_length)
// NOLINTBEGIN(runtime/int)

#include <stdbool.h>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <cstdlib>
)";

constexpr absl::string_view kCommonFooter =
    R"(
// NOLINTEND(whitespace/line_length)
// NOLINTEND(runtime/int)
)";

constexpr absl::string_view kHeaderHeader =
    R"(// NOLINT(build/header_guard)
#pragma once

)";

constexpr absl::string_view kHostHeader = R"(
#include <memory>

#include "$0absl/log/check.h"
#include "$0absl/status/status.h"
#include "$0absl/strings/str_cat.h"
#include "$0absl/types/span.h"
#include "$0sandboxed_api/vars.h"
#include "$0sandboxed_api/sandbox.h"
#include "$0sandboxed_api/lwbox/runtime/sandbox_config.h"

__attribute__((weak))
std::unique_ptr<sandbox2::Policy> $1SandboxModifyPolicy(
    sandbox2::PolicyBuilder* builder) {
  return builder->BuildOrDie();
}

struct $1SandboxImpl : public $1Sandbox {
  static $1SandboxImpl* Instance() {
    static $1SandboxImpl instance;
    return &instance;
  }

  $1SandboxImpl() : $1Sandbox(CreateSandboxConfig()) { Check(Init()); }

  void Check(const absl::Status& status) {
    CHECK_OK(status) << "SAPI sandbox $1 failed";
  }

  size_t CheckedMultiply(size_t x, size_t y) {
#if __has_builtin(__builtin_mul_overflow)
    size_t result;
    CHECK(!__builtin_mul_overflow(x, y, &result));
    return result;
#else
    size_t result = x * y;
    if (y != 0)
      CHECK_EQ(result / y, x);
    return result;
#endif
  }

  static sapi::SandboxConfig CreateSandboxConfig() {
    sandbox2::PolicyBuilder builder =
        sapi::lwbox::DefaultPolicyBuilder();
    return {
        .environment_variables =
            sapi::SandboxConfig::DefaultEnvironmentVariables(),
        .command_line_flags = sapi::SandboxConfig::DefaultFlags(),
        .sandbox2 = {
            .policy = $1SandboxModifyPolicy(&builder),
            .shared_memory_config =
                sandbox2::SharedMemoryConfig{
                    .size = (128ULL << 20),
                    .enable_huge_pages = true,
                },
            .enable_shared_memory_comms = true,
            .enable_multithreading = true,
            // We're permissive with limits by default to not break libraries
            // that might use a lot of memory/cpu.
            .limits = sandbox2::Limits()
                          .set_rlimit_as(RLIM64_INFINITY)
                          .set_rlimit_cpu(RLIM64_INFINITY)
                          .set_rlimit_fsize(RLIM64_INFINITY)
                          .set_rlimit_nofile(RLIM64_INFINITY)
                          .set_rlimit_core(RLIM64_INFINITY)
                          .set_walltime_limit(absl::ZeroDuration()),
        },
    };
  }
};

)";

// Returns sorted function pointers from the IR library by function name.
std::vector<const ir::Function*> GetSortedFunctions(
    const ir::Library& library) {
  std::vector<const ir::Function*> sorted;
  sorted.reserve(library.functions.size());
  for (const auto& func : library.functions) {
    sorted.push_back(&func);
  }
  std::sort(sorted.begin(), sorted.end(),
            [](const ir::Function* a, const ir::Function* b) {
              return a->name < b->name;
            });
  return sorted;
}

// Emits `#include` directives for headers specified in GeneratorOptions.
void EmitLibraryHeaders(const GeneratorOptions& options, std::string& out) {
  std::vector<std::string> sorted_headers(options.library_headers.begin(),
                                          options.library_headers.end());
  std::sort(sorted_headers.begin(), sorted_headers.end());
  for (const auto& header : sorted_headers) {
    absl::StrAppendFormat(&out, "#include \"%s\"\n", header);
  }
}

// Consumes a leading C identifier from `s`, modifying `s` in place. Returns
// true if an identifier was consumed.
bool ConsumeIdentifier(absl::string_view& s) {
  size_t len = 0;
  while (len < s.size() && ((len == 0 ? absl::ascii_isalpha(s[len])
                                      : absl::ascii_isalnum(s[len])) ||
                            s[len] == '_')) {
    ++len;
  }
  s.remove_prefix(len);
  return len > 0;
}

// Compiles a context binding expression (e.g. "$name" or "$name * 2") into
// a runtime lookup against sapi::lwbox::ContextBindingRegistry.
std::string CompileBindingExpr(absl::string_view context_var,
                               absl::string_view expr) {
  if (!absl::StrContains(expr, '$')) {
    absl::string_view rest = expr;
    if (ConsumeIdentifier(rest) && rest.empty()) {
      return absl::Substitute(
          "sapi::lwbox::ContextBindingRegistry::Instance()->GetSize($0, "
          "\"$1\")",
          context_var, expr);
    }
    return std::string(expr);
  }

  // Scan for `$name` references. Anything else, including a `$` that is not
  // followed by an identifier, is passed through unchanged.
  std::string result;
  size_t pos = 0;
  while (pos < expr.size()) {
    if (expr[pos] != '$') {
      result.push_back(expr[pos]);
      ++pos;
      continue;
    }
    size_t id_begin = pos + 1;
    absl::string_view rest = expr.substr(id_begin);
    if (!ConsumeIdentifier(rest)) {
      result.push_back(expr[pos]);
      ++pos;
      continue;
    }
    size_t id_end = expr.size() - rest.size();
    absl::SubstituteAndAppend(
        &result,
        "sapi::lwbox::ContextBindingRegistry::Instance()->GetSize($0, \"$1\")",
        context_var, expr.substr(id_begin, id_end - id_begin));
    pos = id_end;
  }
  return result;
}

// Returns true if a buffer is emitted through the dedicated null-terminated
// C-string path (`sapi::v::ConstCStr` / `sapi::v::Reg<const char*>`) rather
// than the generic buffer machinery.
//
// The IR represents every null-terminated pointer as a `BufferParam` with
// `kNullTerminated` bounds; picking an emission strategy for it is an emitter
// concern. Strings that additionally carry a retain or copy-from-and-bind
// annotation stay on the generic path, which is the only one that emits that
// binding code (`clear_bindings` is emitted independently per parameter).
bool UsesCStringEmission(const ir::BufferParam& buf) {
  return std::holds_alternative<ir::bounds::NullTerminated>(buf.bounds) &&
         !buf.context_bound.copy_from_and_bind.has_value() &&
         !buf.context_bound.retain_and_bind.has_value();
}

// Computes the maximum allocation capacity in bytes for a buffer parameter.
// Capacity is always in bytes.
std::string GetParamCapacityAsBytesExpr(const ir::Parameter& param,
                                        const ir::BufferParam& buf) {
  return std::visit(
      absl::Overload{
          [&](const ir::bounds::Singleton&) {
            DCHECK(!param.type.is_pointee_void())
                << "void* buffer parameter must have byte-based bounds";
            return absl::Substitute("sizeof(*$0)", param.name);
          },
          [&](const ir::bounds::ElemCount& elem) {
            DCHECK(!param.type.is_pointee_void())
                << "void* buffer parameter cannot use element-count bounds";
            return absl::Substitute(
                "sandbox->CheckedMultiply(sizeof(*$0), ($1))", param.name,
                elem.size_expr);
          },
          [](const ir::bounds::ByteCount& byte) { return byte.size_expr; },
          [&](const ir::bounds::ElemSizedByOutparam& elem) {
            DCHECK(!elem.capacity_expr.empty());
            return elem.capacity_expr;
          },
          [&](const ir::bounds::ByteSizedByOutparam& byte) {
            DCHECK(!byte.capacity_expr.empty());
            return byte.capacity_expr;
          },
          [](const ir::bounds::SizedByBinding& binding) {
            std::string context_var = ResolveContextName(binding.context_expr);
            return CompileBindingExpr(context_var, binding.binding_name);
          },
          [&](const ir::bounds::NullTerminated&) {
            return absl::Substitute(
                "strlen(reinterpret_cast<const char*>($0)) + 1", param.name);
          },
      },
      buf.bounds);
}

// Computes the active data size in bytes for a buffer parameter.
std::string GetParamSizeAsBytesExpr(const ir::Parameter& param,
                                    const ir::BufferParam& buf) {
  return std::visit(
      absl::Overload{
          [&](const ir::bounds::Singleton&) {
            DCHECK(!param.type.is_pointee_void())
                << "void* buffer parameter must have byte-based bounds";
            return absl::Substitute("sizeof(*$0)", param.name);
          },
          [&](const ir::bounds::ElemCount& elem) {
            DCHECK(!param.type.is_pointee_void())
                << "void* buffer parameter cannot use element-count bounds";
            return absl::Substitute(
                "sandbox->CheckedMultiply(sizeof(*$0), ($1))", param.name,
                elem.size_expr);
          },
          [&](const ir::bounds::ElemSizedByOutparam& elem) {
            DCHECK(!param.type.is_pointee_void())
                << "void* buffer parameter cannot use element-count bounds";
            return absl::Substitute(
                "sandbox->CheckedMultiply(sizeof(*$0), (*$1))", param.name,
                elem.outparam_name);
          },
          [](const ir::bounds::ByteCount& byte) { return byte.size_expr; },
          [](const ir::bounds::ByteSizedByOutparam& byte) {
            return absl::StrCat("*", byte.outparam_name);
          },
          [](const ir::bounds::SizedByBinding& binding) {
            std::string context_var = ResolveContextName(binding.context_expr);
            return CompileBindingExpr(context_var, binding.binding_name);
          },
          [&](const ir::bounds::NullTerminated&) {
            return absl::Substitute(
                "strlen(reinterpret_cast<const char*>($0)) + 1", param.name);
          },
      },
      buf.bounds);
}

// Returns true if buffer sizing depends on an output parameter (e.g. *out_len).
bool IsSizeBasedOnDerefOutParam(const ir::BufferParam& buf) {
  return std::holds_alternative<ir::bounds::ElemSizedByOutparam>(buf.bounds) ||
         std::holds_alternative<ir::bounds::ByteSizedByOutparam>(buf.bounds);
}

// -----------------------------------------------------------------------------
// Parameter & Wrapper Declaration Helpers
// -----------------------------------------------------------------------------

// Helper to retrieve the return type of a callback parameter.
std::string GetCallbackReturnType(const ir::CallbackParam& cb) {
  return cb.return_value != nullptr ? cb.return_value->type.canonical_name
                                    : "void";
}

// Returns true if the callback returns a pointer.
bool CallbackReturnsPointer(const ir::CallbackParam& cb) {
  return cb.return_value != nullptr && cb.return_value->type.is_pointer();
}

// Helper to extract canonical parameter types of a callback.
std::vector<std::string> GetCallbackParamTypes(const ir::CallbackParam& cb) {
  std::vector<std::string> types;
  types.reserve(cb.callback_parameters.size());
  for (const auto& param : cb.callback_parameters) {
    types.push_back(param.type.canonical_name);
  }
  return types;
}

// Emits the C++ parameter type declaration for the host wrapper.
std::string EmitHostParamDecl(const ir::Parameter& param) {
  return std::visit(
      absl::Overload{
          [&](const ir::CallbackParam& cb) {
            std::string ret_type = GetCallbackReturnType(cb);
            auto param_types = GetCallbackParamTypes(cb);
            if (cb.functor_template_name.has_value()) {
              return absl::Substitute(
                  "$0<$1($2)> $3", *cb.functor_template_name, ret_type,
                  absl::StrJoin(param_types, ", "), param.name);
            }
            return absl::Substitute("$0 (*$1)($2)", ret_type, param.name,
                                    absl::StrJoin(param_types, ", "));
          },
          [&](const auto& p) {
            using T = std::decay_t<decltype(p)>;
            static_assert(
                IsOneOf<T, ir::VoidParam, ir::ScalarParam, ir::BufferParam,
                        ir::CppStringParam, ir::OpaquePointerParam,
                        ir::StructSyncParam>,
                "Unhandled parameter payload type in EmitHostParamDecl!");
            return absl::Substitute("$0 $1", param.type.canonical_name,
                                    param.name);
          },
      },
      param.payload);
}

// Emits the C++ parameter type declaration for the sandboxee RPC wrapper.
// For strings and string references, LenValStruct pointers or data/size pairs
// are used.
std::string EmitSandboxeeParamDecl(const ir::Parameter& param) {
  return std::visit(
      absl::Overload{
          [&](const ir::CallbackParam& cb) {
            return absl::Substitute(
                "$0 (*$1)($2)", GetCallbackReturnType(cb), param.name,
                absl::StrJoin(GetCallbackParamTypes(cb), ", "));
          },
          [&](const ir::CppStringParam& str) {
            if (str.form == ir::CppStringParam::Form::kView ||
                str.form == ir::CppStringParam::Form::kValue ||
                (str.form == ir::CppStringParam::Form::kReference &&
                 str.is_const)) {
              return absl::Substitute("const char* $0_data, size_t $0_size",
                                      param.name);
            }
            return absl::Substitute("sapi::LenValStruct* $0", param.name);
          },
          [&](const auto& p) {
            using T = std::decay_t<decltype(p)>;
            static_assert(
                IsOneOf<T, ir::VoidParam, ir::ScalarParam, ir::BufferParam,
                        ir::OpaquePointerParam, ir::StructSyncParam>,
                "Unhandled parameter payload type in EmitSandboxeeParamDecl!");
            return absl::Substitute("$0 $1", param.type.canonical_name,
                                    param.name);
          },
      },
      param.payload);
}

// -----------------------------------------------------------------------------
// Host Emission Helpers
// -----------------------------------------------------------------------------

// Emits pre-call memory allocation and data synchronization for struct pointer
// members annotated with SANDBOX_STRUCT_SYNC.
std::string EmitStructMemberSyncsPreCall(
    const ir::Parameter& param, const ir::StructSyncParam& sync_param) {
  std::string ret;
  for (const auto& sync : sync_param.members) {
    std::string member_terminal =
        sync.member_name.empty() ? sync.access_path() : sync.member_name;
    std::string suffix = absl::StrCat(param.name, "_", member_terminal);
    std::string host_ptr_expr = sync.access_path();

    std::string size_calc = std::visit(
        absl::Overload{
            [&](const ir::bounds::NullTerminated&) {
              return absl::Substitute(
                  "sapi_member_size_$0 = "
                  "strlen(reinterpret_cast<const char*>($1)) + 1;\n",
                  suffix, host_ptr_expr);
            },
            [&](const ir::bounds::SizedByBinding& binding) {
              std::string context_var =
                  ResolveContextName(binding.context_expr);
              std::string size_expr =
                  CompileBindingExpr(context_var, binding.binding_name);
              return absl::Substitute("sapi_member_size_$0 = $1;\n", suffix,
                                      size_expr);
            },
            [&](const ir::bounds::ByteCount& byte) {
              return absl::Substitute("sapi_member_size_$0 = $1$2;\n", suffix,
                                      sync.parent_prefix, byte.size_expr);
            },
            [&](const ir::bounds::ElemCount& elem) {
              return absl::Substitute(
                  "sapi_member_size_$0 = "
                  "sandbox->CheckedMultiply(sizeof(*($1)), ($2$3));\n",
                  suffix, host_ptr_expr, sync.parent_prefix, elem.size_expr);
            },
            [&](const auto& b) {
              using T = std::decay_t<decltype(b)>;
              static_assert(IsOneOf<T, ir::bounds::Singleton,
                                    ir::bounds::ElemSizedByOutparam,
                                    ir::bounds::ByteSizedByOutparam>,
                            "Unhandled struct member bounds in "
                            "EmitStructMemberSyncsPreCall!");
              return absl::Substitute("sapi_member_size_$0 = sizeof(*($1));\n",
                                      suffix, host_ptr_expr);
            },
        },
        sync.bounds);

    std::string copy_code;
    if (sync.direction == PointerDir::kIn ||
        sync.direction == PointerDir::kInOut) {
      copy_code = absl::Substitute(
          R"(sandbox->Check(
     sandbox->rpc_channel()
         ->CopyToSandbox(
             reinterpret_cast<uintptr_t>(sapi_sb_copy_$0),
             absl::MakeSpan(reinterpret_cast<const char*>($1),
                            sapi_member_size_$0))
         .status());
)",
          suffix, host_ptr_expr);
    }

    std::string update_host_to_sb_ptr_code = absl::Substitute(
        R"(sapi_tmp_$0.mutable_data()->$1 =
   reinterpret_cast<decltype(sapi_tmp_$0.mutable_data()->$1)>(
       sapi_sb_copy_$2);
)",
        param.name, member_terminal, suffix);

    absl::SubstituteAndAppend(&ret,
                              R"(  void* sapi_sb_copy_$0 = nullptr;
  size_t sapi_member_size_$0 = 0;
  if ($1 != nullptr && $2 != nullptr) {
    // Compute size
    $3
    // Allocate
    sandbox->Check(sandbox->rpc_channel()->Allocate(
        sapi_member_size_$0, &sapi_sb_copy_$0));
    // copy host to sb if needed
    $4
    // update ptr member (host to sb)
    $5
  }
)",
                              suffix, param.name, host_ptr_expr, size_calc,
                              copy_code, update_host_to_sb_ptr_code);
  }
  return ret;
}

// Emits post-call data synchronization from sandbox to host for struct pointer
// members, and either retains the remote pointer in ContextBindingRegistry or
// frees the temporary sandbox allocation.
std::string EmitStructMemberSyncsPostCall(
    const ir::Parameter& param, const ir::StructSyncParam& sync_param) {
  std::string out;
  for (const auto& sync : sync_param.members) {
    std::string member_terminal =
        sync.member_name.empty() ? sync.access_path() : sync.member_name;
    std::string suffix = absl::StrCat(param.name, "_", member_terminal);
    std::string host_ptr_expr = sync.access_path();

    if (sync.direction == PointerDir::kOut ||
        sync.direction == PointerDir::kInOut) {
      absl::SubstituteAndAppend(&out,
                                R"(  if (sapi_sb_copy_$0 != nullptr) {
    sapi::lwbox::SyncFromSandboxToHost(
        *sandbox, reinterpret_cast<uintptr_t>(sapi_sb_copy_$0),
        reinterpret_cast<void*>($1), sapi_member_size_$0);
  }
)",
                                suffix, host_ptr_expr);
    }
    if (sync.context_bound.retain_and_bind.has_value()) {
      std::string ctx_name =
          ResolveContextName(sync.context_bound.retain_and_bind->context);
      absl::SubstituteAndAppend(
          &out,
          R"(  if (sapi_sb_copy_$0 != nullptr && $1 != nullptr) {
    sapi::lwbox::ContextBindingRegistry::Instance()->RetainPointer(
        $1, "$2", reinterpret_cast<uintptr_t>(sapi_sb_copy_$0),
        sapi_member_size_$0);
  }
)",
          suffix, ctx_name, sync.context_bound.retain_and_bind->binding_name);
    } else {
      absl::SubstituteAndAppend(&out,
                                R"(  if (sapi_sb_copy_$0 != nullptr) {
    sandbox->Check(sandbox->rpc_channel()->Free(sapi_sb_copy_$0));
  }
)",
                                suffix);
    }
  }
  return out;
}

// Emits code to synchronize a returned or out-parameter pointer from the
// sandboxee, allocating a host buffer and caching/binding it in the
// ContextBindingRegistry. If already bound, synchronizes the existing host copy
// or re-binds if the remote sandbox pointer changed.
std::string EmitCopyFromAndBindOutPtrCode(
    const CopyFromAndBindOutPtr& cb, absl::string_view out_ptr_name,
    absl::string_view out_ptr_type, const ir::BufferBounds& buffer_bounds) {
  std::string ctx_name = ResolveContextName(cb.context);
  std::string size_calc;
  std::string alloc_and_copy_code;

  if (const auto* byte = std::get_if<ir::bounds::ByteCount>(&buffer_bounds)) {
    size_calc =
        absl::Substitute("size_t sapi_binding_size = $0;\n", byte->size_expr);
    alloc_and_copy_code = R"(
        sapi_host_copy = calloc(sapi_binding_size, sizeof(char));
        sapi::lwbox::SyncFromSandboxToHost(
            *sandbox, sapi_sb_ptr, sapi_host_copy, sapi_binding_size);
)";
  } else if (const auto* elem =
                 std::get_if<ir::bounds::ElemCount>(&buffer_bounds)) {
    size_calc = absl::Substitute(
        "size_t sapi_binding_size = "
        "sandbox->CheckedMultiply(sizeof(*sapi_returned_sb_ptr), ($0));\n",
        elem->size_expr);
    alloc_and_copy_code = R"(
        sapi_host_copy = calloc(sapi_binding_size, sizeof(char));
        sapi::lwbox::SyncFromSandboxToHost(
            *sandbox, sapi_sb_ptr, sapi_host_copy, sapi_binding_size);
)";
  } else if (std::holds_alternative<ir::bounds::NullTerminated>(
                 buffer_bounds)) {
    alloc_and_copy_code = R"(
        absl::StatusOr<std::string> sapi_remote_str =
            sandbox->GetCString(sapi::v::RemotePtr(
                reinterpret_cast<const void*>(sapi_sb_ptr)));
        sandbox->Check(sapi_remote_str.status());
        size_t sapi_binding_size = sapi_remote_str->size();
        sapi_host_copy = calloc(sapi_binding_size + 1, sizeof(char));
        memcpy(sapi_host_copy, sapi_remote_str->data(), sapi_binding_size);
)";
  } else if (const auto* binding =
                 std::get_if<ir::bounds::SizedByBinding>(&buffer_bounds)) {
    std::string context_var = ResolveContextName(binding->context_expr);
    std::string size_expr =
        CompileBindingExpr(context_var, binding->binding_name);
    size_calc = absl::Substitute("size_t sapi_binding_size = $0;\n", size_expr);
    alloc_and_copy_code = R"(
        sapi_host_copy = calloc(sapi_binding_size, sizeof(char));
        sapi::lwbox::SyncFromSandboxToHost(
            *sandbox, sapi_sb_ptr, sapi_host_copy, sapi_binding_size);
)";
  }

  // The `else` branch below reuses the host buffer recorded when the binding
  // was first created, and syncs it using `sapi_bound_buf->bytes`, the size
  // captured at bind time. If the sandboxee has since grown the buffer, only
  // the original number of bytes is copied back and the host copy is stale.
  // TODO(b/491828958): Re-read the current size instead of reusing the size
  // captured at bind time.
  return absl::Substitute(
      R"(  {  // Get or create context binding.
    auto* sapi_returned_sb_ptr = $2.GetValue();
    if (sapi_returned_sb_ptr != nullptr && $0 != nullptr) {
      uintptr_t sapi_sb_ptr = reinterpret_cast<uintptr_t>(sapi_returned_sb_ptr);
      void* sapi_host_copy = nullptr;
      auto sapi_bound_buf =
          sapi::lwbox::ContextBindingRegistry::Instance()
              ->GetBoundHostBuffer($0, "$1");
      if (!sapi_bound_buf.has_value() ||
          sapi_bound_buf->remote_ptr != sapi_sb_ptr) {
        $3$4        sapi::lwbox::ContextBindingRegistry::Instance()
            ->BindHostBuffer($0, "$1", sapi_sb_ptr, sapi_host_copy,
                             sapi_binding_size);
      } else {
        sapi_host_copy = sapi_bound_buf->host_ptr;
        sapi::lwbox::SyncFromSandboxToHost(
            *sandbox, sapi_sb_ptr, sapi_host_copy, sapi_bound_buf->bytes);
      }
      $2.SetValue(reinterpret_cast<$5>(sapi_host_copy));
    }
  }
)",
      ctx_name, cb.binding_name, out_ptr_name, size_calc, alloc_and_copy_code,
      out_ptr_type);
}

// -----------------------------------------------------------------------------
// Callback Helpers
// -----------------------------------------------------------------------------

// Returns true if the callback returns a pointer or if any of its parameters
// are pointers or annotated buffers. In these cases, we must wrap the callback
// in a host-side lambda trampoline to perform translation, syncing, or
// tracking.
bool NeedsCallbackLambdaWrapper(const ir::CallbackParam& cb) {
  if (CallbackReturnsPointer(cb)) {
    return true;
  }
  for (const auto& p : cb.callback_parameters) {
    bool needs_wrap = std::visit(
        absl::Overload{
            [](const ir::BufferParam&) { return true; },
            [&](const auto& inner) {
              using T = std::decay_t<decltype(inner)>;
              static_assert(IsOneOf<T, ir::VoidParam, ir::ScalarParam,
                                    ir::CppStringParam, ir::OpaquePointerParam,
                                    ir::StructSyncParam, ir::CallbackParam>,
                            "Unhandled callback parameter payload in "
                            "NeedsCallbackLambdaWrapper!");
              return p.direction().has_value();
            },
        },
        p.payload);
    if (needs_wrap) return true;
  }
  return false;
}

// Computes the size in bytes for a callback return buffer.
std::string GetCallbackReturnSizeAsBytesExpr(const ir::Parameter& cb_param,
                                             const ir::CallbackParam& cb) {
  std::string ret_host_var = absl::StrCat("sapi_", cb_param.name, "_ret_host");
  const auto* ret_buf =
      cb.return_value ? cb.return_value->As<ir::BufferParam>() : nullptr;
  if (ret_buf == nullptr) {
    return absl::Substitute("sizeof(*$0)", ret_host_var);
  }
  return std::visit(
      absl::Overload{
          [&](const ir::bounds::Singleton&) {
            return absl::Substitute("sizeof(*$0)", ret_host_var);
          },
          [&](const ir::bounds::ElemCount& elem) {
            return absl::Substitute(
                "sandbox->CheckedMultiply(sizeof(*$0), ($1))", ret_host_var,
                elem.size_expr);
          },
          [](const ir::bounds::ByteCount& byte) { return byte.size_expr; },
          [&](const ir::bounds::NullTerminated&) {
            return absl::Substitute(
                "strlen(reinterpret_cast<const char*>($0)) + 1", ret_host_var);
          },
          [&](const auto& b) {
            using T = std::decay_t<decltype(b)>;
            static_assert(IsOneOf<T, ir::bounds::ElemSizedByOutparam,
                                  ir::bounds::ByteSizedByOutparam,
                                  ir::bounds::SizedByBinding>,
                          "Unhandled callback return bounds in "
                          "GetCallbackReturnSizeAsBytesExpr!");
            return absl::Substitute("sizeof(*$0)", ret_host_var);
          },
      },
      ret_buf->bounds);
}

// Emits parameter marshaling blocks (pre-call and post-call) for a host-side
// callback wrapper lambda given the callback's parameter list.
void EmitCallbackParamMarshaling(absl::Span<const ir::Parameter> parameters,
                                 std::vector<std::string>& lambda_params,
                                 std::vector<std::string>& lambda_call_args,
                                 std::vector<std::string>& pre_call_blocks,
                                 std::string& param_sync_post_call) {
  lambda_params.reserve(parameters.size());
  lambda_call_args.reserve(parameters.size());
  pre_call_blocks.reserve(parameters.size());

  for (const auto& p : parameters) {
    std::string p_name = p.name;
    std::string p_type = p.type.canonical_name;
    lambda_params.push_back(absl::Substitute("$0 $1", p_type, p_name));

    std::visit(
        absl::Overload{
            [&](const ir::BufferParam& p_buf) {
              lambda_call_args.push_back(absl::StrCat("sapi_host_", p_name));
              if (UsesCStringEmission(p_buf)) {
                pre_call_blocks.push_back(absl::Substitute(
                    R"(      std::optional<std::string> sapi_str_$0;
      $1 sapi_host_$0 = nullptr;
      if ($0 != nullptr) {
        auto sapi_cstr_status = sandbox->GetCString(
            sapi::v::RemotePtr(const_cast<char*>(
                reinterpret_cast<const char*>($0))));
        sandbox->Check(sapi_cstr_status.status());
        sapi_str_$0 = std::move(*sapi_cstr_status);
        sapi_host_$0 = sapi_str_$0->c_str();
      })",
                    p_name, p_type));
                return;
              }
              std::string size_expr;
              if (const auto* byte =
                      std::get_if<ir::bounds::ByteCount>(&p_buf.bounds)) {
                size_expr = byte->size_expr;
              } else if (const auto* elem = std::get_if<ir::bounds::ElemCount>(
                             &p_buf.bounds)) {
                size_expr = absl::Substitute(
                    "sandbox->CheckedMultiply(sizeof(*$0), ($1))", p_name,
                    elem->size_expr);
              } else {
                size_expr = absl::Substitute("sizeof(*$0)", p_name);
              }
              std::string maybe_transfer_from =
                  p_buf.direction == PointerDir::kOut
                      ? ""
                      : absl::Substitute(
                            "        "
                            "sandbox->Check(sandbox->"
                            "TransferFromSandboxee(&sapi_arr_$0."
                            "value()));\n",
                            p_name);
              pre_call_blocks.push_back(absl::Substitute(
                  R"(      $1 sapi_host_$0 = nullptr;
      std::optional<sapi::v::Array<char>> sapi_arr_$0;
      if ($0 != nullptr) {
        sapi_arr_$0.emplace($2);
        sapi_arr_$0->SetRemote(
            const_cast<void*>(reinterpret_cast<const void*>($0)));
$3        sapi_host_$0 = reinterpret_cast<$1>(sapi_arr_$0->GetData());
      })",
                  p_name, p_type, size_expr, maybe_transfer_from));
              if (p_buf.direction == PointerDir::kOut ||
                  p_buf.direction == PointerDir::kInOut) {
                absl::SubstituteAndAppend(
                    &param_sync_post_call,
                    R"(      if (sapi_arr_$0.has_value()) {
        sandbox->Check(sandbox->TransferToSandboxee(&sapi_arr_$0.value()));
      }
)",
                    p_name);
              }
            },
            [&](const ir::OpaquePointerParam& op) {
              lambda_call_args.push_back(absl::StrCat("sapi_host_", p_name));
              if (op.host_opaque_handle.has_value()) {
                if (const auto* alias =
                        std::get_if<ir::lifetime::AliasHostPtr>(&op.lifetime)) {
                  pre_call_blocks.push_back(absl::Substitute(
                      R"(      $1 sapi_expected_$0 =
          $2 == nullptr ? nullptr : reinterpret_cast<$1>($3);
      CHECK_EQ($0, sapi_expected_$0);
      $1 sapi_host_$0 = $2;)",
                      p_name, p_type, alias->host_param_name,
                      *op.host_opaque_handle));
                  return;
                }
              }
              pre_call_blocks.push_back(absl::Substitute(
                  R"(      $1 sapi_host_$0 = $0;)", p_name, p_type));
            },
            [&](const auto& inner) {
              using T = std::decay_t<decltype(inner)>;
              static_assert(
                  IsOneOf<T, ir::VoidParam, ir::ScalarParam, ir::CppStringParam,
                          ir::StructSyncParam, ir::CallbackParam>,
                  "Unhandled callback parameter payload in "
                  "EmitCallbackParamMarshaling!");
              if (p.direction().has_value()) {
                lambda_call_args.push_back(absl::StrCat("sapi_host_", p_name));
                std::string size_expr = absl::Substitute("sizeof(*$0)", p_name);
                std::string maybe_transfer_from =
                    p.direction() == PointerDir::kOut
                        ? ""
                        : absl::Substitute(
                              "        "
                              "sandbox->Check(sandbox->"
                              "TransferFromSandboxee(&sapi_arr_$0."
                              "value()));\n",
                              p_name);
                pre_call_blocks.push_back(absl::Substitute(
                    R"(      $1 sapi_host_$0 = nullptr;
      std::optional<sapi::v::Array<char>> sapi_arr_$0;
      if ($0 != nullptr) {
        sapi_arr_$0.emplace($2);
        sapi_arr_$0->SetRemote(
            const_cast<void*>(reinterpret_cast<const void*>($0)));
$3        sapi_host_$0 = reinterpret_cast<$1>(sapi_arr_$0->GetData());
      })",
                    p_name, p_type, size_expr, maybe_transfer_from));
                if (p.direction() == PointerDir::kOut ||
                    p.direction() == PointerDir::kInOut) {
                  absl::SubstituteAndAppend(
                      &param_sync_post_call,
                      R"(      if (sapi_arr_$0.has_value()) {
        sandbox->Check(sandbox->TransferToSandboxee(&sapi_arr_$0.value()));
      }
)",
                      p_name);
                }
              } else {
                lambda_call_args.push_back(p_name);
              }
            },
        },
        p.payload);
  }
}

// Emits host pre-call setup for callback arguments. Simple scalar callbacks are
// passed directly, while pointer/buffer callbacks are wrapped in a lambda
// trampoline that synchronizes parameters into host memory before invocation
// and transfers callback return values to sandbox memory.
std::string EmitCallbackHostPreCall(const ir::Parameter& cb_param,
                                    const ir::CallbackParam& cb) {
  if (!NeedsCallbackLambdaWrapper(cb)) {
    return absl::Substitute(
        R"(  std::optional<sapi::v::Callback> sapi_cb_$0;
  if ($0) {
    sapi_cb_$0.emplace($0);
    sandbox->Check(sandbox->Allocate(&sapi_cb_$0.value(),
                                     /*automatic_free=*/true));
  }
)",
        cb_param.name);
  }

  std::string ret_vars;
  std::string cb_ret_type = GetCallbackReturnType(cb);
  bool is_ret_ptr = CallbackReturnsPointer(cb);
  if (is_ret_ptr) {
    absl::SubstituteAndAppend(&ret_vars,
                              "  std::vector<std::unique_ptr<sapi::v::Var>> "
                              "sapi_cb_ret_vars_$0;\n",
                              cb_param.name);
    if (cb.is_callback_return_aliased) {
      absl::SubstituteAndAppend(&ret_vars,
                                "  absl::flat_hash_map<uintptr_t, void*> "
                                "sapi_alias_cb_return_map_$0;\n",
                                cb_param.name);
    }
  }

  std::vector<std::string> lambda_params;
  std::vector<std::string> lambda_call_args;
  std::vector<std::string> pre_call_blocks;
  std::string param_sync_post_call;
  EmitCallbackParamMarshaling(cb.callback_parameters, lambda_params,
                              lambda_call_args, pre_call_blocks,
                              param_sync_post_call);

  std::string param_sync_pre_call;
  if (!pre_call_blocks.empty()) {
    param_sync_pre_call =
        absl::StrCat(absl::StrJoin(pre_call_blocks, "\n\n"), "\n\n");
  }

  std::string lambda_call_str = absl::StrJoin(lambda_call_args, ", ");
  std::string lambda_body;

  if (is_ret_ptr) {
    std::string ret_size_expr = GetCallbackReturnSizeAsBytesExpr(cb_param, cb);
    std::string alias_map_code;
    if (cb.is_callback_return_aliased) {
      alias_map_code = absl::Substitute(
          "      "
          "sapi_alias_cb_return_map_$0[reinterpret_cast<uintptr_t>(\n"
          "          sapi_ret_var->GetRemote())] = "
          "sapi_$0_ret_host;\n",
          cb_param.name);
    }
    std::string transfer_code;
    bool ret_uninitialized =
        cb.uninitialized ||
        (cb.return_value && cb.return_value->uninitialized());
    if (!ret_uninitialized) {
      transfer_code =
          "      "
          "sandbox->Check(sandbox->TransferToSandboxee(sapi_ret_var."
          "get()));\n";
    }
    std::string maybe_post_call =
        param_sync_post_call.empty() ? ""
                                     : absl::StrCat(param_sync_post_call, "\n");
    lambda_body = absl::Substitute(
        R"($0      // Forward params -> args, and do the callback
      $1 sapi_$2_ret_host = $2($3);
$7      // If the callback returned null, no need to
      // allocate a sandbox copy, sync, etc.
      if (!sapi_$2_ret_host) {
        return nullptr;
      }
      // Otherwise, make a sandbox copy of the
      // return value, and return the sandbox copy.

      size_t ret_size_bytes = $4;
      auto sapi_ret_var = std::make_unique<sapi::v::Array<char>>(
          reinterpret_cast<char*>(sapi_$2_ret_host), ret_size_bytes);
      sandbox->Check(sandbox->Allocate(sapi_ret_var.get(),
                                       /*automatic_free=*/true));
$5$6      auto ret_remote_ptr = sapi_ret_var->GetRemote();
      sapi_cb_ret_vars_$2.push_back(std::move(sapi_ret_var));
      return reinterpret_cast<$1>(ret_remote_ptr);
)",
        param_sync_pre_call, cb_ret_type, cb_param.name, lambda_call_str,
        ret_size_expr, transfer_code, alias_map_code, maybe_post_call);
  } else if (cb_ret_type == "void") {
    if (param_sync_post_call.empty()) {
      lambda_body = absl::Substitute(
          R"($0      // Forward params -> args, and do the callback
      $1($2);
)",
          param_sync_pre_call, cb_param.name, lambda_call_str);
    } else {
      lambda_body = absl::Substitute(
          R"($0      // Forward params -> args, and do the callback
      $1($2);

$3)",
          param_sync_pre_call, cb_param.name, lambda_call_str,
          param_sync_post_call);
    }
  } else {
    if (param_sync_post_call.empty()) {
      lambda_body = absl::Substitute(
          R"($0      // Forward params -> args, and do the callback
      $1 sapi_$2_ret = $2($3);
      return sapi_$2_ret;
)",
          param_sync_pre_call, cb_ret_type, cb_param.name, lambda_call_str);
    } else {
      lambda_body = absl::Substitute(
          R"($0      // Forward params -> args, and do the callback
      $1 sapi_$2_ret = $2($3);

$4      return sapi_$2_ret;
)",
          param_sync_pre_call, cb_ret_type, cb_param.name, lambda_call_str,
          param_sync_post_call);
    }
  }

  std::string lambda_params_str = absl::StrJoin(lambda_params, ", ");

  return absl::Substitute(
      R"(  std::optional<sapi::v::Callback> sapi_cb_$0;
  // Variables to track callback return values, etc.
$1  // If the callback is not null, set the sapi_cb var to a lambda.
  if ($0) {
    auto sapi_lambda_$0 = [&]($2) -> $3 {
$4    };
    sapi_cb_$0.emplace(sapi_lambda_$0);
    sandbox->Check(sandbox->Allocate(&sapi_cb_$0.value(),
                                     /*automatic_free=*/true));
  }
)",
      cb_param.name, ret_vars, lambda_params_str, cb_ret_type, lambda_body);
}

}  // namespace

void EmitFuncDecl(std::string& out, const ir::Function& func) {
  std::string ret = "void";
  if (func.return_value) {
    ret = func.return_value->type.canonical_name;
  }
  absl::StrAppend(&out,
                  absl::Substitute("extern \"C\" $0 $1(", ret, func.name));
  for (size_t i = 0; i < func.parameters.size(); ++i) {
    if (i > 0) {
      absl::StrAppend(&out, ", ");
    }
    absl::StrAppend(&out, EmitHostParamDecl(func.parameters[i]));
  }
  absl::StrAppend(&out, ")");
}

void EmitWrapperDecl(std::string& out, const ir::Function& func) {
  std::string ret = "void";
  absl::StrAppend(
      &out,
      absl::Substitute("extern \"C\" __attribute__((used, retain)) $0 $1$2(",
                       ret, kWrapperPrefix, func.name));
  bool first = true;
  for (const auto& param : func.parameters) {
    if (!first) {
      absl::StrAppend(&out, ", ");
    }
    first = false;
    absl::StrAppend(&out, EmitSandboxeeParamDecl(param));
  }

  if (func.return_value) {
    if (!first) {
      absl::StrAppend(&out, ", ");
    }
    if (func.return_value->type.kind == ir::TypeKind::kString) {
      absl::StrAppend(&out, "sapi::LenValStruct* sapi_ret_arg");
    } else {
      absl::StrAppend(&out, func.return_value->type.canonical_name,
                      "* sapi_ret_arg");
    }
  }

  absl::StrAppend(&out, ")");
}

namespace {

absl::StatusOr<std::string> FinalizeCode(
    absl::string_view body, bool is_header, bool add_includes,
    const absl::flat_hash_set<std::string>& includes) {
  std::string out;
  if (is_header) {
    out.append(kHeaderHeader);
  }
  out.append(kCommonHeader);
  if (add_includes) {
    std::vector<std::string> sorted_includes(includes.begin(), includes.end());
    std::sort(sorted_includes.begin(), sorted_includes.end());
    for (const auto& inc : sorted_includes) {
      absl::StrAppendFormat(&out, "#include %s\n", inc);
    }
  }
  absl::StrAppend(&out, "\n", body, kCommonFooter);
  return ReformatGoogleStyle("input", out);
}

// -----------------------------------------------------------------------------
// EmitSandboxeeHdr
// -----------------------------------------------------------------------------

bool HasStringType(const ir::Library& library) {
  for (const auto& func : library.functions) {
    if (func.return_value &&
        func.return_value->type.kind == ir::TypeKind::kString) {
      return true;
    }
    for (const auto& param : func.parameters) {
      bool uses_lenval = std::visit(
          absl::Overload{
              [](const ir::CppStringParam& str) {
                return str.form == ir::CppStringParam::Form::kPointer ||
                       (str.form == ir::CppStringParam::Form::kReference &&
                        !str.is_const);
              },
              [](const auto& p) {
                using T = std::decay_t<decltype(p)>;
                static_assert(IsOneOf<T, ir::VoidParam, ir::ScalarParam,
                                      ir::BufferParam, ir::OpaquePointerParam,
                                      ir::StructSyncParam, ir::CallbackParam>,
                              "Unhandled parameter payload in HasStringType!");
                return false;
              },
          },
          param.payload);
      if (uses_lenval) return true;
    }
  }
  return false;
}

}  // namespace

absl::StatusOr<std::string> EmitSandboxeeHdr(
    const GeneratorOptions& options, const ir::Library& library,
    const absl::flat_hash_set<std::string>& includes) {
  std::string out;
  EmitLibraryHeaders(options, out);
  absl::StrAppend(&out, "\n");

  std::vector<const ir::Function*> sorted_funcs = GetSortedFunctions(library);

  for (const auto* func : sorted_funcs) {
    if (func->sandboxee_thunk) {
      continue;
    }
    EmitWrapperDecl(out, *func);
    absl::StrAppend(&out, ";\n");
  }

  absl::flat_hash_set<std::string> sandboxee_includes = includes;
  if (HasStringType(library)) {
    sandboxee_includes.insert(
        absl::Substitute("\"$0sandboxed_api/lenval_core.h\"", kIncludePrefix));
  }

  return FinalizeCode(out, /*is_header=*/true, /*add_includes=*/true,
                      sandboxee_includes);
}

// -----------------------------------------------------------------------------
// EmitSandboxeeSrc
// -----------------------------------------------------------------------------

absl::StatusOr<std::string> EmitSandboxeeSrc(
    const GeneratorOptions& options, const ir::Library& library,
    const absl::flat_hash_set<std::string>& includes) {
  std::string out;
  EmitLibraryHeaders(options, out);

  if (library.sandboxee_code) {
    absl::StrAppend(&out, *library.sandboxee_code, "\n\n");
  }

  std::vector<const ir::Function*> sorted_funcs = GetSortedFunctions(library);

  for (const auto* func : sorted_funcs) {
    EmitFuncDecl(out, *func);
    absl::StrAppend(&out, ";\n\n");
    if (func->sandboxee_thunk) {
      absl::StrAppend(&out, "// Start of thunk\n", "extern \"C\" ",
                      func->sandboxee_thunk->body, "\n// End of thunk\n\n");
    } else {
      EmitWrapperDecl(out, *func);
      absl::StrAppend(&out, " {\n");

      std::vector<std::string> call_args;
      call_args.reserve(func->parameters.size());
      std::string post_call_code;

      for (size_t i = 0; i < func->parameters.size(); ++i) {
        const auto& param = func->parameters[i];
        std::visit(
            absl::Overload{
                [&](const ir::CppStringParam& str) {
                  if (str.form == ir::CppStringParam::Form::kView) {
                    call_args.push_back(absl::Substitute(
                        "std::string_view($0_data, $0_size)", param.name));
                  } else if (str.form == ir::CppStringParam::Form::kValue ||
                             (str.form ==
                                  ir::CppStringParam::Form::kReference &&
                              str.is_const)) {
                    call_args.push_back(absl::Substitute(
                        "std::string($0_data, $0_size)", param.name));
                  } else if (str.form == ir::CppStringParam::Form::kReference) {
                    absl::StrAppend(
                        &out,
                        absl::Substitute(
                            "  std::string "
                            "sapi_tmp_$0(reinterpret_cast<char*>($0->data), "
                            "$0->size);\n"
                            "  free($0->data);\n\n",
                            param.name));
                    call_args.push_back(absl::StrCat("sapi_tmp_", param.name));
                    absl::SubstituteAndAppend(
                        &post_call_code,
                        "  $0->size = sapi_tmp_$0.size();\n"
                        "  $0->data = "
                        "reinterpret_cast<uint8_t*>(malloc($0->size));\n"
                        "  if ($0->size > 0) {\n"
                        "    memcpy($0->data, sapi_tmp_$0.data(), "
                        "$0->size);\n"
                        "  }\n",
                        param.name);
                  } else {
                    // kPointer
                    absl::StrAppend(
                        &out,
                        absl::Substitute(
                            "  std::string* sapi_tmp_ptr_$0 = nullptr;\n"
                            "  std::string sapi_tmp_$0;\n"
                            "  if ($0 != nullptr) {\n"
                            "    sapi_tmp_$0 = "
                            "std::string(reinterpret_cast<char*>($0->data), "
                            "$0->size);\n"
                            "    free($0->data);\n"
                            "    sapi_tmp_ptr_$0 = &sapi_tmp_$0;\n"
                            "  }\n",
                            param.name));
                    call_args.push_back(
                        absl::StrCat("sapi_tmp_ptr_", param.name));
                    if (str.direction == PointerDir::kOut ||
                        str.direction == PointerDir::kInOut) {
                      absl::SubstituteAndAppend(
                          &post_call_code,
                          "  if ($0 != nullptr) {\n"
                          "    $0->size = sapi_tmp_$0.size();\n"
                          "    $0->data = "
                          "reinterpret_cast<uint8_t*>(malloc($0->size));\n"
                          "    if ($0->size > 0) {\n"
                          "      memcpy($0->data, sapi_tmp_$0.data(), "
                          "$0->size);\n"
                          "    }\n"
                          "  }\n",
                          param.name);
                    }
                  }
                },
                [&](const auto& p) {
                  using T = std::decay_t<decltype(p)>;
                  static_assert(IsOneOf<T, ir::VoidParam, ir::ScalarParam,
                                        ir::BufferParam, ir::OpaquePointerParam,
                                        ir::StructSyncParam, ir::CallbackParam>,
                                "Unhandled parameter payload type in sandboxee "
                                "call arguments!");
                  call_args.push_back(param.name);
                },
            },
            param.payload);
      }

      std::string call_args_str = absl::StrJoin(call_args, ", ");
      std::string target_call =
          absl::Substitute("$0($1)", func->name, call_args_str);

      if (func->return_value) {
        if (func->return_value->type.kind == ir::TypeKind::kString) {
          absl::SubstituteAndAppend(
              &out,
              "  std::string sapi_ret_val = $0;\n"
              "  sapi_ret_arg->size = sapi_ret_val.size();\n"
              "  sapi_ret_arg->data = "
              "reinterpret_cast<uint8_t*>(malloc(sapi_ret_arg->size));\n"
              "  if (sapi_ret_arg->size > 0) {\n"
              "    memcpy(sapi_ret_arg->data, sapi_ret_val.data(), "
              "sapi_ret_arg->size);\n"
              "  }\n",
              target_call);
        } else {
          // Using auto avoids potential syntax errors with complex return
          // types (e.g., function pointers).
          absl::SubstituteAndAppend(&out,
                                    "  auto sapi_ret_val = $0;\n"
                                    "  *sapi_ret_arg = sapi_ret_val;\n",
                                    target_call);
        }
      } else {
        absl::StrAppend(&out, "  ", target_call, ";\n");
      }

      absl::StrAppend(&out, post_call_code);
      absl::StrAppend(&out, "}\n\n");
    }
  }

  absl::flat_hash_set<std::string> sandboxee_includes = includes;
  if (HasStringType(library)) {
    sandboxee_includes.insert(
        absl::Substitute("\"$0sandboxed_api/lenval_core.h\"", kIncludePrefix));
  }
  for (const auto* func : sorted_funcs) {
    if (func->return_value &&
        func->return_value->type.kind == ir::TypeKind::kString) {
      sandboxee_includes.insert("<string>");
    }
    for (const auto& param : func->parameters) {
      std::visit(
          absl::Overload{
              [&](const ir::CppStringParam& str) {
                if (str.form == ir::CppStringParam::Form::kView) {
                  sandboxee_includes.insert("<string_view>");
                } else if (str.form == ir::CppStringParam::Form::kPointer) {
                  sandboxee_includes.insert("<string>");
                  sandboxee_includes.insert("<memory>");
                } else {
                  sandboxee_includes.insert("<string>");
                }
              },
              [&](const auto& p) {
                using T = std::decay_t<decltype(p)>;
                static_assert(IsOneOf<T, ir::VoidParam, ir::ScalarParam,
                                      ir::BufferParam, ir::OpaquePointerParam,
                                      ir::StructSyncParam, ir::CallbackParam>,
                              "Unhandled parameter payload in EmitSandboxeeSrc "
                              "includes!");
              },
          },
          param.payload);
    }
  }

  return FinalizeCode(out, /*is_header=*/false, /*add_includes=*/true,
                      sandboxee_includes);
}

// -----------------------------------------------------------------------------
// EmitSandboxeeMain
// -----------------------------------------------------------------------------

absl::StatusOr<std::string> EmitSandboxeeMain(const GeneratorOptions& options,
                                              const ir::Library& library) {
  std::string out;
  std::vector<const ir::Function*> sorted_funcs = GetSortedFunctions(library);
  for (const auto* func : sorted_funcs) {
    absl::StrAppend(&out, "extern \"C\" void ", func->name, "();\n");
  }
  absl::StrAppend(&out, "\nint main() {\n");
  for (const auto* func : sorted_funcs) {
    absl::StrAppend(&out, "  ", func->name, "();\n");
  }
  absl::StrAppend(&out, "}\n");
  return FinalizeCode(out, /*is_header=*/false, /*add_includes=*/false, {});
}

// -----------------------------------------------------------------------------
// EmitHostSrc
// -----------------------------------------------------------------------------

namespace {

void EmitHostSrcParam(const ir::Parameter& param, std::string& pre_call,
                      std::string& call_args, std::string& post_call) {
  std::visit(
      absl::Overload{
          [&](const ir::CallbackParam& cb) {
            absl::StrAppend(&pre_call, EmitCallbackHostPreCall(param, cb));
            absl::StrAppend(
                &call_args,
                absl::Substitute(
                    "sapi_cb_$0 ? sapi_cb_$0->PtrBefore() : nullptr",
                    param.name));
            if (NeedsCallbackLambdaWrapper(cb) && CallbackReturnsPointer(cb) &&
                cb.return_value->IsOutput()) {
              absl::SubstituteAndAppend(
                  &post_call,
                  "  for (auto& var : sapi_cb_ret_vars_$0) {\n"
                  "    "
                  "sandbox->Check(sandbox->TransferFromSandboxee(var."
                  "get()));\n"
                  "  }\n",
                  param.name);
            }
          },
          [&](const ir::CppStringParam& str) {
            if (str.form == ir::CppStringParam::Form::kView ||
                str.form == ir::CppStringParam::Form::kValue ||
                (str.form == ir::CppStringParam::Form::kReference &&
                 str.is_const)) {
              absl::StrAppend(
                  &pre_call,
                  absl::Substitute("  sapi::v::Array<char> "
                                   "sapi_tmp_$0(const_cast<char*>($0.data()), "
                                   "$0.size());\n",
                                   param.name));
              absl::StrAppend(
                  &call_args,
                  absl::Substitute("sapi_tmp_$0.PtrBefore(), $0.size()",
                                   param.name));
            } else if (str.form == ir::CppStringParam::Form::kReference) {
              absl::StrAppend(&pre_call,
                              absl::Substitute("  sapi::v::LenVal sapi_tmp_$0("
                                               "const_cast<char*>($0.data()), "
                                               "$0.size());\n",
                                               param.name));
              absl::StrAppend(
                  &call_args,
                  absl::Substitute("sapi_tmp_$0.PtrBoth()", param.name));
              absl::SubstituteAndAppend(
                  &post_call,
                  "  $0.resize(sapi_tmp_$0.GetDataSize());\n"
                  "  memcpy(const_cast<char*>($0.data()), "
                  "sapi_tmp_$0.GetData(), "
                  "$0.size());\n",
                  param.name);
            } else {
              // kPointer
              absl::StrAppend(
                  &pre_call,
                  absl::Substitute(
                      "  std::unique_ptr<sapi::v::LenVal> sapi_tmp_$0;\n"
                      "  if ($0 != nullptr) {\n"
                      "    sapi_tmp_$0 = "
                      "std::make_unique<sapi::v::LenVal>("
                      "$0->data(), "
                      "$0->size());\n"
                      "  }\n",
                      param.name));
              absl::StrAppend(
                  &call_args,
                  absl::Substitute(
                      "sapi_tmp_$0 ? sapi_tmp_$0->PtrBoth() : nullptr",
                      param.name));
              absl::SubstituteAndAppend(
                  &post_call,
                  "  if ($0 != nullptr && sapi_tmp_$0) {\n"
                  "    $0->assign("
                  "reinterpret_cast<char*>(sapi_tmp_$0->GetData()), "
                  "sapi_tmp_$0->GetDataSize());\n"
                  "  }\n",
                  param.name);
            }
          },
          [&](const ir::OpaquePointerParam& op) {
            if (op.host_opaque_handle.has_value()) {
              absl::StrAppend(
                  &pre_call,
                  absl::Substitute(
                      "  sapi::v::RemotePtr sapi_tmp_$0($0 == nullptr ? "
                      "nullptr : reinterpret_cast<void*>($1));\n",
                      param.name, *op.host_opaque_handle));
            } else {
              absl::StrAppend(
                  &pre_call,
                  absl::Substitute("  sapi::v::RemotePtr sapi_tmp_$0($0);\n",
                                   param.name));
            }
            absl::StrAppend(
                &call_args,
                absl::Substitute("$0 == nullptr ? nullptr : &sapi_tmp_$0",
                                 param.name));
          },
          [&](const ir::StructSyncParam& sync) {
            std::string struct_type =
                param.type.unqualified_pointee_type_name();
            absl::StrAppend(
                &pre_call,
                absl::Substitute(
                    "  sapi::v::Struct<$0> sapi_tmp_$1($1 != nullptr ? *$1 "
                    ": ($0){});\n",
                    struct_type, param.name));
            if (!sync.members.empty()) {
              absl::StrAppend(&pre_call,
                              EmitStructMemberSyncsPreCall(param, sync));
            }
            std::string ptr_access =
                (param.direction() == PointerDir::kIn)
                    ? "PtrBefore()"
                    : ((param.direction() == PointerDir::kOut) ? "PtrAfter()"
                                                               : "PtrBoth()");
            absl::StrAppend(
                &call_args,
                absl::Substitute("$0 == nullptr ? nullptr : sapi_tmp_$0.$1",
                                 param.name, ptr_access));
            if (!sync.members.empty()) {
              std::string save_ptrs;
              std::string restore_ptrs;
              for (const auto& s : sync.members) {
                // Allow the sandbox to modify sandbox opaque members, and
                // don't restore them.
                if (s.direction == PointerDir::kSandboxOpaque) continue;
                std::string member_terminal =
                    s.member_name.empty() ? s.access_path() : s.member_name;
                std::string suffix =
                    absl::StrCat(param.name, "_", member_terminal);
                std::string host_ptr_expr = s.access_path();
                absl::SubstituteAndAppend(
                    &save_ptrs, "    const auto sapi_host_ptr_$0 = $1;\n",
                    suffix, host_ptr_expr);
                absl::SubstituteAndAppend(&restore_ptrs,
                                          "    if ($0 != nullptr) {\n"
                                          "      $0 = sapi_host_ptr_$1;\n"
                                          "    }\n",
                                          host_ptr_expr, suffix);
              }
              if (param.direction() != PointerDir::kIn &&
                  !param.type.is_const) {
                absl::SubstituteAndAppend(
                    &post_call,
                    "  if ($0 != nullptr) {\n"
                    "    // Save original host pointers\n"
                    "$1"
                    "    // Sync post-call sandbox data to the struct\n"
                    "    if ($0 != nullptr) {\n"
                    "      *$0 = sapi_tmp_$0.data();\n"
                    "    }\n"
                    "    // Restore original host pointers\n"
                    "$2"
                    "  }\n",
                    param.name, save_ptrs, restore_ptrs);
              }
              absl::StrAppend(&post_call,
                              EmitStructMemberSyncsPostCall(param, sync));
            } else if (param.direction() == PointerDir::kOut ||
                       param.direction() == PointerDir::kInOut) {
              absl::StrAppend(&post_call,
                              absl::Substitute("  if ($0 != nullptr) {\n"
                                               "    *$0 = sapi_tmp_$0.data();\n"
                                               "  }\n",
                                               param.name));
            }
          },
          [&](const ir::BufferParam& buf) {
            if (UsesCStringEmission(buf)) {
              if (buf.direction == PointerDir::kIn) {
                absl::StrAppend(
                    &pre_call,
                    absl::Substitute("  sapi::v::ConstCStr sapi_tmp_$0($0);\n",
                                     param.name));
                absl::StrAppend(
                    &call_args,
                    absl::Substitute("sapi_tmp_$0.PtrBefore()", param.name));
              } else if (buf.direction == PointerDir::kOut &&
                         std::holds_alternative<ir::lifetime::SandboxGlobal>(
                             buf.lifetime)) {
                absl::StrAppend(&pre_call,
                                absl::Substitute("  sapi::v::Reg<const char*> "
                                                 "sapi_tmp_$0(nullptr);\n",
                                                 param.name));
                absl::StrAppend(
                    &call_args,
                    absl::Substitute("sapi_tmp_$0.PtrAfter()", param.name));
                absl::SubstituteAndAppend(
                    &post_call,
                    "  if ($0 != nullptr) {\n"
                    "    *$0 = "
                    "sapi::lwbox::GlobalStringRegistry::Instance()"
                    "->GetOrFetch(*sandbox, sapi_tmp_$0.GetValue());\n"
                    "  }\n",
                    param.name);
              } else if (buf.direction == PointerDir::kInOut &&
                         std::holds_alternative<ir::lifetime::SandboxGlobal>(
                             buf.lifetime)) {
                absl::SubstituteAndAppend(
                    &pre_call,
                    R"(  std::unique_ptr<sapi::v::ConstCStr> sapi_cstr_$0;
  const char* remote_$0 = nullptr;
  if ($0 != nullptr && *$0 != nullptr) {
    sapi_cstr_$0 = std::make_unique<sapi::v::ConstCStr>(*$0);
    sandbox->Check(sandbox->Allocate(sapi_cstr_$0.get(),
                   /*automatic_free=*/true));
    sandbox->Check(sandbox->TransferToSandboxee(sapi_cstr_$0.get()));
    remote_$0 = reinterpret_cast<const char*>(sapi_cstr_$0->GetRemote());
  }
  sapi::v::Reg<const char*> sapi_tmp_$0(remote_$0);
)",
                    param.name);
                absl::StrAppend(
                    &call_args,
                    absl::Substitute("sapi_tmp_$0.PtrBoth()", param.name));
                absl::SubstituteAndAppend(
                    &post_call,
                    "  if ($0 != nullptr) {\n"
                    "    *$0 = "
                    "sapi::lwbox::GlobalStringRegistry::Instance()"
                    "->GetOrFetch(*sandbox, sapi_tmp_$0.GetValue());\n"
                    "  }\n",
                    param.name);
              }
              return;
            }
            if (buf.context_bound.copy_from_and_bind.has_value()) {
              std::string pointee_type =
                  param.type.unqualified_pointee_type_name();
              absl::StrAppend(
                  &pre_call,
                  absl::Substitute("  sapi::v::Reg<$0> sapi_tmp_$1(nullptr);\n",
                                   pointee_type, param.name));
              std::string ptr_access =
                  (buf.direction == PointerDir::kIn)
                      ? "PtrBefore()"
                      : ((buf.direction == PointerDir::kOut) ? "PtrAfter()"
                                                             : "PtrBoth()");
              absl::StrAppend(
                  &call_args,
                  absl::Substitute("$0 == nullptr ? nullptr : sapi_tmp_$0.$1",
                                   param.name, ptr_access));
              absl::StrAppend(&post_call,
                              EmitCopyFromAndBindOutPtrCode(
                                  *buf.context_bound.copy_from_and_bind,
                                  absl::StrCat("sapi_tmp_", param.name),
                                  pointee_type, buf.bounds));
              absl::SubstituteAndAppend(&post_call,
                                        "  if ($0 != nullptr) {\n"
                                        "    *$0 = sapi_tmp_$0.GetValue();\n"
                                        "  }\n",
                                        param.name);
            } else if (param.type.is_pointee_record() &&
                       !buf.context_bound.retain_and_bind.has_value() &&
                       std::holds_alternative<ir::bounds::Singleton>(
                           buf.bounds)) {
              // Single unannotated struct pointers (`Singleton`) use
              // `sapi::v::Struct<T>`, which owns a stack-allocated `T`
              // value (`sapi_tmp_<param>.data()`) initialized from
              // `*<param>` (or `{}` when `<param> == nullptr`) and writes
              // back `*<param> = sapi_tmp_<param>.data()` on
              // `kOut`/`kInOut`.
              //
              // All explicitly sized or retained struct buffers
              // (`ElemCount`, `ByteCount`, `SizedByBinding`,
              // `*SizedByOutparam`, `retain_and_bind`) intentionally fall
              // through to the generic `sapi::v::Array<char>` byte-buffer
              // path below rather than emitting `sapi::v::Array<T>`. See
              // the comment on `sapi::v::Array<char>` below for why this is
              // both overflow-safe and well-defined in C++.
              std::string struct_type =
                  param.type.unqualified_pointee_type_name();
              absl::StrAppend(
                  &pre_call,
                  absl::Substitute(
                      "  sapi::v::Struct<$0> sapi_tmp_$1($1 != nullptr ? "
                      "*$1 : ($0){});\n",
                      struct_type, param.name));
              std::string ptr_access =
                  (param.direction() == PointerDir::kIn)
                      ? "PtrBefore()"
                      : ((param.direction() == PointerDir::kOut) ? "PtrAfter()"
                                                                 : "PtrBoth()");
              absl::StrAppend(
                  &call_args,
                  absl::Substitute("$0 == nullptr ? nullptr : sapi_tmp_$0.$1",
                                   param.name, ptr_access));
              if (param.direction() == PointerDir::kOut ||
                  param.direction() == PointerDir::kInOut) {
                absl::StrAppend(
                    &post_call,
                    absl::Substitute("  if ($0 != nullptr) {\n"
                                     "    *$0 = sapi_tmp_$0.data();\n"
                                     "  }\n",
                                     param.name));
              }
            } else {
              std::string cap_expr = GetParamCapacityAsBytesExpr(param, buf);
              std::string size_expr = GetParamSizeAsBytesExpr(param, buf);
              bool is_deref_outparam = IsSizeBasedOnDerefOutParam(buf);

              if (buf.context_bound.retain_and_bind.has_value()) {
                absl::SubstituteAndAppend(
                    &pre_call,
                    "  sapi::v::RemotePtr sapi_tmp_$0(nullptr);\n"
                    "  if ($0 != nullptr) {\n"
                    "    void* sapi_sb_ptr = nullptr;\n"
                    "    sandbox->Check(\n"
                    "        sandbox->rpc_channel()->Allocate("
                    "$1, &sapi_sb_ptr));\n"
                    "    sapi_tmp_$0 = sapi::v::RemotePtr(sapi_sb_ptr);\n"
                    "  }\n",
                    param.name, cap_expr);
                if (param.direction() == PointerDir::kIn ||
                    param.direction() == PointerDir::kInOut) {
                  absl::SubstituteAndAppend(
                      &pre_call,
                      "  if ($0 != nullptr) {\n"
                      "    sandbox->Check(\n"
                      "        sandbox->rpc_channel()\n"
                      "            ->CopyToSandbox("
                      "sapi_tmp_$0.GetRemoteValue(),\n"
                      "                            "
                      "absl::MakeSpan(reinterpret_cast<const char*>($0),\n"
                      "                                           $1))\n"
                      "            .status());\n"
                      "  }\n",
                      param.name, cap_expr);
                }
                absl::StrAppend(
                    &call_args,
                    absl::Substitute("$0 == nullptr ? nullptr : &sapi_tmp_$0",
                                     param.name));

                if (param.direction() == PointerDir::kOut ||
                    param.direction() == PointerDir::kInOut) {
                  absl::SubstituteAndAppend(
                      &post_call,
                      "  if (sapi_tmp_$0.GetRemoteValue() != 0) {\n"
                      "    sapi::lwbox::SyncFromSandboxToHost(\n"
                      "        *sandbox, sapi_tmp_$0.GetRemoteValue(),\n"
                      "        reinterpret_cast<void*>($0), $1);\n"
                      "  }\n",
                      param.name, cap_expr);
                }
              } else {
                // Wrap every non-retained buffer (scalars, void*, and
                // sized struct arrays) in `sapi::v::Array<char>` with the
                // byte capacity `cap_expr` rather than `sapi::v::Array<T>`:
                //
                // 1. Overflow safety: `sapi::v::Array<T>(T*, size_t nelem)`
                //    computes `total_size_ = nelem * sizeof(T)` with an
                //    unchecked `*`. Routing `ElemCount` through `cap_expr`
                //    emits `sandbox->CheckedMultiply(sizeof(*p), (nelem))`
                //    so integer overflow traps via `CHECK` before
                //    allocating or copying.
                // 2. Strict aliasing & object representation:
                //    `arg_converter.cc` enforces that buffer pointees are
                //    trivially copyable (`IsDeeplyTriviallyCopyableType`).
                //    Under C++ [basic.lval] and [basic.types.general], any
                //    trivially copyable `T[N]` object representation can be
                //    accessed and copied through `char*` / `const char*`
                //    without violating strict aliasing.
                // 3. `const_cast` safety: `sapi::v::Array<const T>` already
                //    performs `SetLocal(const_cast<T*>(arr_))` internally
                //    to store `void*` in `sapi::v::Var`. Casting away
                //    `const` on the pointer is well-defined
                //    ([expr.const.cast]) because `const` buffers have
                //    `PointerDir::kIn`
                //    (`PtrBefore()`), which only reads `[GetLocal(),
                //    GetLocal() + GetSize())` via `CopyToSandbox` and never
                //    writes through the pointer.
                // 4. Sandboxee alignment: `sapi::v::Var::Allocate` passes
                //    only the byte count `GetSize()` to
                //    `rpc_channel()->Allocate`, which calls `malloc(size)`
                //    in the sandboxee (`alignof(std::max_align_t)`),
                //    independent of `Array`'s element type `T`.
                absl::StrAppend(
                    &pre_call,
                    absl::Substitute(
                        "  sapi::v::Array<char> "
                        "sapi_tmp_$0(const_cast<char*>(reinterpret_cast<"
                        "const char*>($0)), $1);\n",
                        param.name, cap_expr));
              }

              if (is_deref_outparam) {
                absl::StrAppend(
                    &pre_call,
                    absl::Substitute(
                        "  if ($0 != nullptr) {\n"
                        "    "
                        "sandbox->Check(sandbox->Allocate(&sapi_tmp_$0, "
                        "/*automatic_free=*/true));\n"
                        "  }\n",
                        param.name));
                if (param.direction() == PointerDir::kInOut ||
                    param.direction() == PointerDir::kIn) {
                  absl::StrAppend(
                      &pre_call,
                      absl::Substitute(
                          "  if ($0 != nullptr) {\n"
                          "    "
                          "sandbox->Check("
                          "sandbox->rpc_channel()->CopyToSandbox(\n"
                          "        "
                          "reinterpret_cast<uintptr_t>("
                          "sapi_tmp_$0.GetRemote()),\n"
                          "        absl::MakeSpan(reinterpret_cast<const "
                          "char*>($0), "
                          "$1)).status());\n"
                          "  }\n",
                          param.name, size_expr));
                }
                absl::StrAppend(
                    &call_args,
                    absl::Substitute(
                        "$0 == nullptr ? nullptr : sapi_tmp_$0.PtrNone()",
                        param.name));
                absl::StrAppend(
                    &post_call,
                    absl::Substitute(
                        "  if ($0 != nullptr) {\n"
                        "    size_t sapi_final_size = $1;\n"
                        "    size_t sapi_cap_size = $2;\n"
                        "    if (sapi_final_size > sapi_cap_size) {\n"
                        "      sandbox->Check(absl::OutOfRangeError(\n"
                        "          absl::StrCat(\"Sandboxee returned size "
                        "(\", sapi_final_size,\n"
                        "                       \") exceeding capacity "
                        "(\", "
                        "sapi_cap_size, \") for param $0\")));\n"
                        "    }\n"
                        "    sandbox->Check(\n"
                        "        sandbox->rpc_channel()\n"
                        "            ->CopyFromSandbox(\n"
                        "                "
                        "reinterpret_cast<uintptr_t>(sapi_tmp_$0."
                        "GetRemote()),\n"
                        "                "
                        "absl::MakeSpan("
                        "reinterpret_cast<char*>($0), sapi_final_size))\n"
                        "            .status());\n"
                        "  }\n",
                        param.name, size_expr, cap_expr));
              } else if (!buf.context_bound.retain_and_bind.has_value()) {
                std::string ptr_access =
                    (param.direction() == PointerDir::kIn)
                        ? "PtrBefore()"
                        : ((param.direction() == PointerDir::kOut)
                               ? "PtrAfter()"
                               : "PtrBoth()");
                absl::StrAppend(
                    &call_args,
                    absl::Substitute("$0 == nullptr ? nullptr : sapi_tmp_$0.$1",
                                     param.name, ptr_access));
              }
            }

            if (buf.context_bound.retain_and_bind.has_value() &&
                param.type.is_pointer()) {
              std::string ctx_name = ResolveContextName(
                  buf.context_bound.retain_and_bind->context);
              std::string cap_expr = GetParamCapacityAsBytesExpr(param, buf);
              absl::SubstituteAndAppend(
                  &post_call,
                  "  if (sapi_tmp_$0.GetRemoteValue() != 0 && $1 != "
                  "nullptr) "
                  "{\n"
                  "    "
                  "sapi::lwbox::ContextBindingRegistry::Instance()->"
                  "RetainPointer(\n"
                  "        $1, \"$2\", sapi_tmp_$0.GetRemoteValue(), $3);\n"
                  "  }\n",
                  param.name, ctx_name,
                  buf.context_bound.retain_and_bind->binding_name, cap_expr);
            }
          },
          [&](const auto& p) {
            using T = std::decay_t<decltype(p)>;
            static_assert(
                IsOneOf<T, ir::VoidParam, ir::ScalarParam>,
                "Unhandled parameter payload type in host call args!");
            absl::StrAppend(&call_args, param.name);
          },
      },
      param.payload);
}

absl::flat_hash_set<std::string> GatherHostIncludes(
    const ir::Library& library,
    absl::Span<const ir::Function* const> sorted_funcs,
    const absl::flat_hash_set<std::string>& includes) {
  absl::flat_hash_set<std::string> host_includes = includes;
  host_includes.insert(absl::Substitute(
      "\"$0sandboxed_api/lwbox/runtime/lwbox_runtime.h\"", kIncludePrefix));
  if (HasStringType(library)) {
    host_includes.insert(
        absl::Substitute("\"$0sandboxed_api/lenval_core.h\"", kIncludePrefix));
  }
  for (const auto* func : sorted_funcs) {
    for (const auto& param : func->parameters) {
      std::visit(
          absl::Overload{
              [&](const ir::CallbackParam& cb) {
                host_includes.insert("<optional>");
                host_includes.insert(absl::Substitute(
                    "\"$0sandboxed_api/var_callback.h\"", kIncludePrefix));
                if (cb.functor_template_name.has_value()) {
                  if (*cb.functor_template_name == "std::function") {
                    host_includes.insert("<functional>");
                  } else if (*cb.functor_template_name ==
                             "absl::AnyInvocable") {
                    host_includes.insert(absl::Substitute(
                        "\"$0absl/functional/any_invocable.h\"",
                        kIncludePrefix));
                  }
                }
                if (NeedsCallbackLambdaWrapper(cb)) {
                  if (CallbackReturnsPointer(cb)) {
                    host_includes.insert("<vector>");
                    host_includes.insert("<memory>");
                  }
                  if (cb.is_callback_return_aliased) {
                    host_includes.insert(
                        absl::Substitute("\"$0absl/container/flat_hash_map.h\"",
                                         kIncludePrefix));
                  }
                  for (const auto& cb_p : cb.callback_parameters) {
                    std::visit(
                        absl::Overload{
                            [&](const ir::BufferParam& cb_buf) {
                              if (UsesCStringEmission(cb_buf)) {
                                host_includes.insert("<string>");
                                host_includes.insert("<cstring>");
                              }
                            },
                            [&](const auto& p) {
                              using T = std::decay_t<decltype(p)>;
                              static_assert(
                                  IsOneOf<T, ir::VoidParam, ir::ScalarParam,
                                          ir::CppStringParam,
                                          ir::OpaquePointerParam,
                                          ir::StructSyncParam,
                                          ir::CallbackParam>,
                                  "Unhandled callback parameter payload type "
                                  "in includes check!");
                            },
                        },
                        cb_p.payload);
                  }
                }
              },
              [&](const auto& p) {
                using T = std::decay_t<decltype(p)>;
                static_assert(
                    IsOneOf<T, ir::VoidParam, ir::ScalarParam, ir::BufferParam,
                            ir::CppStringParam, ir::OpaquePointerParam,
                            ir::StructSyncParam>,
                    "Unhandled parameter payload in GatherHostIncludes!");
              },
          },
          param.payload);
    }
  }
  return host_includes;
}

}  // namespace

absl::StatusOr<std::string> EmitHostSrc(
    const GeneratorOptions& options, const ir::Library& library,
    const absl::flat_hash_set<std::string>& includes) {
  std::string out;
  absl::StrAppendFormat(&out, "#include \"%s\"\n", options.out_file);
  absl::StrAppend(&out,
                  absl::Substitute(kHostHeader, kIncludePrefix, options.name));

  std::vector<const ir::Function*> sorted_funcs = GetSortedFunctions(library);

  if (library.host_code) {
    absl::StrAppend(&out, *library.host_code, "\n\n");
  }

  for (const auto& src : library.host_state_vars) {
    absl::StrAppend(&out, src, "\n");
  }

  for (const auto* func : sorted_funcs) {
    if (func->host_thunk) {
      absl::StrAppend(&out, "// Start of thunk\n");
      // Forward declare the sandboxee thunk, as the host thunk calls into it.
      if (func->sandboxee_thunk) {
        absl::StrAppend(&out, "extern \"C\" ",
                        func->sandboxee_thunk->declaration, ";\n");
      }
      absl::StrAppend(&out, "extern \"C\" ", func->host_thunk->body,
                      "\n// End of thunk\n\n");
      continue;
    }

    EmitFuncDecl(out, *func);
    absl::StrAppend(
        &out, " {\n",
        absl::Substitute("  auto* sandbox = $0SandboxImpl::Instance();\n",
                         options.name),
        absl::Substitute("  $0Api api(sandbox);\n\n", options.name));

    std::string pre_call;
    std::string call_args;
    std::string post_call;

    for (size_t i = 0; i < func->parameters.size(); ++i) {
      if (i > 0) absl::StrAppend(&call_args, ", ");
      EmitHostSrcParam(func->parameters[i], pre_call, call_args, post_call);
    }

    if (func->return_value) {
      if (!func->parameters.empty()) absl::StrAppend(&call_args, ", ");
      if (func->return_value->type.kind == ir::TypeKind::kString) {
        absl::StrAppend(&pre_call,
                        "  sapi::v::LenVal sapi_ret_tmp(nullptr, 0);\n");
        absl::StrAppend(&call_args, "sapi_ret_tmp.PtrAfter()");
      } else {
        absl::StrAppend(
            &pre_call,
            absl::Substitute("  sapi::v::Reg<$0> sapi_ret_arg;\n",
                             func->return_value->type.canonical_name));
        absl::StrAppend(&call_args, "sapi_ret_arg.PtrAfter()");
      }
    }

    for (const auto& param : func->parameters) {
      if (param.should_clear_bindings()) {
        absl::SubstituteAndAppend(
            &post_call,
            "  sapi::lwbox::ContextBindingRegistry::Instance()->"
            "ClearBindings(*sandbox, $0);\n",
            param.name);
      }
    }

    absl::StrAppend(&out, pre_call, "\n");
    absl::StrAppend(&out,
                    absl::Substitute("  sandbox->Check(api.$0$1($2));\n\n",
                                     kWrapperPrefix, func->name, call_args));
    absl::StrAppend(&out, post_call);

    // Context bound post-call data binding
    for (const auto& bind : func->context_bound.bind_data) {
      std::string ctx_name = ResolveContextName(bind.context);
      absl::StrAppend(
          &out,
          absl::Substitute(
              "  if ($0 != nullptr) {\n"
              "    sapi::lwbox::ContextBindingRegistry::Instance()->BindSize(\n"
              "        $0, \"$2\", $1);\n"
              "  }\n",
              ctx_name, bind.host_computable_expr, bind.binding_name));
    }

    if (func->return_value) {
      std::visit(
          absl::Overload{
              [&](const ir::CppStringParam&) {
                absl::StrAppend(
                    &out,
                    "  return "
                    "std::string(reinterpret_cast<char*>("
                    "sapi_ret_tmp.GetData()), sapi_ret_tmp.GetDataSize());\n");
              },
              [&](const ir::BufferParam& ret_buf) {
                if (const auto* alias = std::get_if<ir::lifetime::AliasHostPtr>(
                        &ret_buf.lifetime)) {
                  absl::StrAppend(
                      &out,
                      absl::Substitute(
                          "  return sapi_ret_arg.GetValue() ? $0 : nullptr;\n",
                          alias->host_param_name));
                } else if (const auto* alias_cb =
                               std::get_if<ir::lifetime::AliasCallbackReturn>(
                                   &ret_buf.lifetime)) {
                  absl::SubstituteAndAppend(
                      &out,
                      "  return sapi_ret_arg.GetValue()\n"
                      "             ? static_cast<$0>(\n"
                      "                   "
                      "sapi_alias_cb_return_map_$1[reinterpret_cast<uintptr_"
                      "t>(\n"
                      "                       sapi_ret_arg.GetValue())])\n"
                      "             : nullptr;\n",
                      func->return_value->type.canonical_name,
                      alias_cb->callback_param_name);
                } else if (ret_buf.context_bound.copy_from_and_bind
                               .has_value()) {
                  absl::StrAppend(&out,
                                  EmitCopyFromAndBindOutPtrCode(
                                      *ret_buf.context_bound.copy_from_and_bind,
                                      "sapi_ret_arg",
                                      func->return_value->type.canonical_name,
                                      ret_buf.bounds));
                  absl::StrAppend(&out, "  return sapi_ret_arg.GetValue();\n");
                } else if (std::holds_alternative<ir::lifetime::SandboxGlobal>(
                               ret_buf.lifetime)) {
                  absl::SubstituteAndAppend(
                      &out,
                      "  return sapi::lwbox::GlobalStringRegistry::Instance()"
                      "->GetOrFetch(*sandbox, sapi_ret_arg.GetValue());\n");
                } else {
                  absl::StrAppend(&out, "  return sapi_ret_arg.GetValue();\n");
                }
              },
              [&](const auto& p) {
                using T = std::decay_t<decltype(p)>;
                static_assert(
                    IsOneOf<T, ir::VoidParam, ir::ScalarParam,
                            ir::OpaquePointerParam, ir::StructSyncParam,
                            ir::CallbackParam>,
                    "Unhandled return value payload type in HostSrc!");
                absl::StrAppend(&out, "  return sapi_ret_arg.GetValue();\n");
              },
          },
          func->return_value->payload);
    }
    absl::StrAppend(&out, "}\n\n");
  }

  absl::flat_hash_set<std::string> host_includes =
      GatherHostIncludes(library, sorted_funcs, includes);
  return FinalizeCode(out, /*is_header=*/false, /*add_includes=*/true,
                      host_includes);
}

}  // namespace sapi
