// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <algorithm>
#include <string>
#include <vector>

#include "absl/strings/str_cat.h"
#include "absl/strings/str_format.h"
#include "absl/strings/string_view.h"
#include "sandboxed_api/tools/clang_generator/arg.h"
#include "sandboxed_api/tools/clang_generator/ast_utils.h"
#include "sandboxed_api/tools/clang_generator/generator.h"
#include "sandboxed_api/tools/clang_generator/sandboxed_library_emitter.h"

namespace sapi {

// TODO(dvyukov): try to prepend a C++ namespace to C++ names
// instead of just adding a prefix. It will make it nicer
// for debuggers/profilers that demangle symbols.
constexpr absl::string_view kWrapperPrefix = "sapi_wrapper_";



// We pre-include some common headers always to avoid more complex logic
// to figure out when we actually need each of them.
// We have to disable whitespace/line_length linter checks because
// some identifiers are longer than the DEC VT52 terminal line length limit.
// We have to disable runtime/int linter checks because after typedef
// resolution we can inject types that are prohibited by linter,
// or if just the library used prohibited types.
constexpr absl::string_view kCommonHeader =
    R"(// Automatically generated by SAPI interface generator; DO NOT EDIT.

// NOLINTBEGIN(whitespace/line_length)
// NOLINTBEGIN(runtime/int)

#include <stdbool.h>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <cstdlib>
)";

constexpr absl::string_view kCommonFooter =
    R"(
// NOLINTEND(whitespace/line_length)
// NOLINTEND(runtime/int)
)";

constexpr absl::string_view kHeaderHeader =
    R"(// NOLINT(build/header_guard)
#pragma once

)";

constexpr absl::string_view kHostHeader = R"(
#include <memory>

#include "$0absl/log/check.h"
#include "$0absl/status/status.h"
#include "$0absl/strings/str_cat.h"
#include "$0absl/types/span.h"
#include "$0sandboxed_api/vars.h"
#include "$0sandboxed_api/sandbox.h"

__attribute__((weak))
std::unique_ptr<sandbox2::Policy> $1SandboxModifyPolicy(
    sandbox2::PolicyBuilder* builder) {
  return builder->BuildOrDie();
}

struct $1SandboxImpl : public $1Sandbox {
  static $1SandboxImpl* Instance() {
    static $1SandboxImpl instance;
    return &instance;
  }

  $1SandboxImpl() : $1Sandbox(CreateSandboxConfig()) { Check(Init()); }

  void Check(const absl::Status& status) {
    CHECK_OK(status) << "SAPI sandbox $1 failed";
  }

  size_t CheckedMultiply(size_t x, size_t y) {
#if __has_builtin(__builtin_mul_overflow)
    size_t result;
    CHECK(!__builtin_mul_overflow(x, y, &result));
    return result;
#else
    size_t result = x * y;
    if (y != 0)
      CHECK_EQ(result / y, x);
    return result;
#endif
  }

  static sapi::SandboxConfig CreateSandboxConfig() {
    sandbox2::PolicyBuilder builder =
        sapi::Sandbox2Config::DefaultPolicyBuilder();
    return {
        .sandbox2 = {
            .policy = $1SandboxModifyPolicy(&builder),
            .shared_memory_config =
                sandbox2::SharedMemoryConfig{.enable_huge_pages = true},
            .enable_shared_memory_comms = true,
        },
    };
  }
};

)";

std::string SandboxedLibraryEmitter::Func::EmitPostCallBindData() const {
  std::string out;
  if (context_bound.bind_data.empty()) return out;

  absl::StrAppend(&out,
                  R"cc({
                         absl::MutexLock sapi_lock(sapi_internal_context_binding_mutex);
                  )cc");

  for (const auto& bind : context_bound.bind_data) {
    std::string ctx_name = ResolveContextName(bind.context);
    // TODO(b/491828958): to start, we abort if the binding already exists.
    // Should we allow overwriting?
    absl::StrAppend(
        &out,
        absl::Substitute(
            R"cc(if ($0 != nullptr) {
                   size_t sapi_bind_val = $1;
                   auto [sapi_it, sapi_inserted] =
                       sapi_internal_context_binding_prim_map.insert_or_assign(
                           std::make_pair($0, "$2"), sapi_bind_val);
                   CHECK(sapi_inserted);
                 }
            )cc",
            ctx_name, bind.host_computable_expr, bind.binding_name));
  }

  absl::StrAppend(&out, "  }\n");
  return out;
}

void SandboxedLibraryEmitter::EmitLibraryHeaders(
    const GeneratorOptions& options, std::string& out) const {
  std::vector<std::string> sorted_headers(options.library_headers.begin(),
                                          options.library_headers.end());
  std::sort(sorted_headers.begin(), sorted_headers.end());
  for (const auto& header : sorted_headers) {
    absl::StrAppendFormat(&out, "#include \"%s\"\n", header);
  }
}

absl::StatusOr<std::string> SandboxedLibraryEmitter::EmitSandboxeeHdr(
    const GeneratorOptions& options) const {
  std::string out;

  EmitLibraryHeaders(options, out);

  for (const auto* func : SortedFuncs()) {
    if (func->sandboxee_thunk) {
      continue;
    }
    EmitWrapperDecl(out, *func);
    absl::StrAppend(&out, ";\n\n");
  }
  return Finalize(out, /*is_header=*/true, /*add_includes=*/true);
}

absl::StatusOr<std::string> SandboxedLibraryEmitter::EmitSandboxeeSrc(
    const GeneratorOptions& options) const {
  std::string out;

  EmitLibraryHeaders(options, out);

  if (sandboxee_code_) {
    absl::StrAppend(&out, *sandboxee_code_);
  }

  for (const auto* func : SortedFuncs()) {
    EmitFuncDecl(out, *func);

    absl::StrAppend(&out, ";\n\n");
    // Emit the thunk on the sandboxee side if we have one.
    if (func->sandboxee_thunk) {
      absl::StrAppend(&out, "// Start of thunk\n", "extern \"C\" ",
                      func->sandboxee_thunk->body, "\n", "// End of thunk\n");
    } else {
      EmitWrapperDecl(out, *func);
      absl::StrAppend(&out, " {\n");
      for (const auto& arg : func->args) {
        absl::StrAppend(&out, arg->EmitSandboxeePreCall());
      }
      absl::StrAppend(&out, "\n");
      if (func->ret) {
        absl::StrAppend(&out, absl::Substitute("$0 sapi_ret_val = ",
                                               func->ret->EmitRetType()));
      }
      // If we have a thunk, we call into that instead of the original library
      // function.
      absl::StrAppend(
          &out,
          func->sandboxee_thunk ? func->sandboxee_thunk->name : func->name,
          "(");
      if (func->sandboxee_thunk) {
        // We need to get the args for the sandboxee thunk here. This is wrong
        // right now.
        for (const auto& arg : func->args) {
          if (&arg != &func->args[0]) {
            absl::StrAppend(&out, ", ");
          }
          absl::StrAppend(&out, arg->EmitSandboxeeArgs());
        }
      } else {
        for (const auto& arg : func->args) {
          if (&arg != &func->args[0]) {
            absl::StrAppend(&out, ", ");
          }
          absl::StrAppend(&out, arg->EmitSandboxeeArgs());
        }
      }
      absl::StrAppend(&out, ");\n\n");
      for (const auto& arg : func->args) {
        absl::StrAppend(&out, arg->EmitSandboxeePostCall());
      }
      if (func->ret) {
        absl::StrAppend(&out, func->ret->EmitSandboxeeRet());
      }
      absl::StrAppend(&out, "}\n\n");
    }
  }
  return Finalize(out, /*is_header=*/false, /*add_includes=*/true);
}

absl::StatusOr<std::string> SandboxedLibraryEmitter::EmitSandboxeeMain(
    const GeneratorOptions& options) const {
  std::string out;
  for (const auto* func : SortedFuncs()) {
    absl::StrAppend(&out, "extern \"C\" void ", func->name, "();\n");
  }
  absl::StrAppend(&out, "\nint main() {\n");
  for (const auto* func : SortedFuncs()) {
    absl::StrAppend(&out, "  ", func->name, "();\n");
  }
  absl::StrAppend(&out, "}\n");
  return Finalize(out, /*is_header=*/false, /*add_includes=*/false);
}

absl::StatusOr<std::string> SandboxedLibraryEmitter::EmitHostSrc(
    const GeneratorOptions& options) const {
  std::string out;
  absl::StrAppendFormat(&out, "#include \"%s\"\n", options.out_file);
  absl::StrAppend(&out,
                  absl::Substitute(kHostHeader, kIncludePrefix, options.name));

  if (host_code_) {
    absl::StrAppend(&out, *host_code_);
  }

  // Emit the host state variables.
  for (const auto& src : host_state_vars_) {
    absl::StrAppend(&out, src, "\n");
  }

  // Emit the host state variables and code needed to support annotations
  // (params, returns, function-level).
  absl::StrAppend(&out, "namespace {\n");
  std::vector<std::string> sorted_arg_host_state_vars(
      arg_host_state_vars_.begin(), arg_host_state_vars_.end());
  std::sort(sorted_arg_host_state_vars.begin(),
            sorted_arg_host_state_vars.end());
  for (const auto& src : sorted_arg_host_state_vars) {
    absl::StrAppend(&out, src, "\n");
  }

  if (has_context_bindings_) {
    absl::StrAppend(&out, EmitContextBindingsHostSupportCode());
  }
  absl::StrAppend(&out, "}  // namespace\n\n");

  for (const auto* func : SortedFuncs()) {
    // Emit the host thunk on the host side if we have one.
    if (func->host_thunk) {
      absl::StrAppend(&out, "// Start of thunk\n");
      // Forward declare the sandboxee thunk as we are going to call it.
      absl::StrAppend(&out,
                      absl::Substitute("extern \"C\" $0;\n\n",
                                       func->sandboxee_thunk->declaration));
      absl::StrAppend(&out, "extern \"C\" ", func->host_thunk->body, "\n",
                      "// End of thunk\n");
    } else {
      EmitFuncDecl(out, *func);
      absl::StrAppend(
          &out, " {\n",
          absl::Substitute("auto* sandbox = $0SandboxImpl::Instance();\n",
                           options.name),
          absl::Substitute("$0Api api(sandbox);\n\n", options.name));
      for (const auto& arg : func->args) {
        absl::StrAppend(&out, arg->EmitHostPreCall());
      }
      if (func->ret) {
        absl::StrAppend(&out, func->ret->EmitRetPreCall());
      }
      absl::StrAppend(&out, "\n",
                      absl::Substitute("sandbox->Check(api.$0$1(",
                                       kWrapperPrefix, func->name));
      for (const auto& arg : func->args) {
        if (&arg != &func->args[0]) {
          absl::StrAppend(&out, ", ");
        }
        absl::StrAppend(&out, arg->EmitHostArgs());
      }
      if (func->ret) {
        if (!func->args.empty()) {
          absl::StrAppend(&out, ", ");
        }
        absl::StrAppend(&out, func->ret->EmitRetArgs());
      }
      absl::StrAppend(&out, "));\n\n");
      for (const auto& arg : func->args) {
        absl::StrAppend(&out, arg->EmitHostPostCall());
      }
      absl::StrAppend(&out, func->EmitPostCallBindData());
      if (func->ret) {
        absl::StrAppend(&out, func->ret->EmitHostRet());
      }
      absl::StrAppend(&out, "}\n\n");
    }
  }
  return Finalize(out, /*is_header=*/false, /*add_includes=*/true);
}

std::string SandboxedLibraryEmitter::EmitContextBindingsHostSupportCode()
    const {
  std::string out;
  // State variables
  absl::StrAppend(&out,
                  R"cc(absl::Mutex sapi_internal_context_binding_mutex;)cc");
  absl::StrAppend(
      &out,
      R"cc(absl::node_hash_map<std::pair<const void*, std::string>, size_t>
               sapi_internal_context_binding_prim_map
                   ABSL_GUARDED_BY(sapi_internal_context_binding_mutex);)cc");
  absl::StrAppend(
      &out,
      R"cc(absl::node_hash_map<std::pair<const void*, std::string>,
                               std::tuple<uintptr_t, size_t, uintptr_t>>
               sapi_internal_context_binding_map
                   ABSL_GUARDED_BY(sapi_internal_context_binding_mutex);)cc");
  absl::StrAppend(
      &out,
      R"cc(absl::node_hash_map<std::pair<const void*, std::string>,
                               std::tuple<uintptr_t, uintptr_t, size_t>>
               sapi_internal_context_retained_binding_map
                   ABSL_GUARDED_BY(sapi_internal_context_binding_mutex);)cc");
  absl::StrAppend(&out, "\n");

  // Helper functions
  absl::StrAppend(
      &out,
      R"cc(
        void sapi_internal_clear_context_bindings(sapi::SandboxBase* sandbox,
                                                  const void* context) {
          if (context == nullptr) return;
          absl::MutexLock sapi_lock(sapi_internal_context_binding_mutex);
          for (auto sapi_it = sapi_internal_context_binding_prim_map.begin();
               sapi_it != sapi_internal_context_binding_prim_map.end();) {
            if (sapi_it->first.first == context) {
              sapi_internal_context_binding_prim_map.erase(sapi_it++);
            } else {
              ++sapi_it;
            }
          }
          for (auto sapi_it = sapi_internal_context_binding_map.begin();
               sapi_it != sapi_internal_context_binding_map.end();) {
            if (sapi_it->first.first == context) {
              auto& sapi_binding_data = sapi_it->second;
              free(reinterpret_cast<void*>(std::get<2>(sapi_binding_data)));
              sapi_internal_context_binding_map.erase(sapi_it++);
            } else {
              ++sapi_it;
            }
          }
          for (auto sapi_it =
                   sapi_internal_context_retained_binding_map.begin();
               sapi_it != sapi_internal_context_retained_binding_map.end();) {
            if (sapi_it->first.first == context) {
              auto& sapi_binding_data = sapi_it->second;
              CHECK(sandbox->rpc_channel()
                        ->Free(reinterpret_cast<void*>(
                            std::get<1>(sapi_binding_data)))
                        .ok());
              sapi_internal_context_retained_binding_map.erase(sapi_it++);
            } else {
              ++sapi_it;
            }
          }
        })cc");

  absl::StrAppend(
      &out,
      R"cc(
        absl::Status sapi_internal_sync_from_sandbox_to_host(
            sapi::SandboxBase* sandbox, uintptr_t remote_ptr,
            uintptr_t host_ptr, size_t size) {
          return sandbox->rpc_channel()
              ->CopyFromSandbox(
                  remote_ptr,
                  absl::MakeSpan(reinterpret_cast<char*>(host_ptr), size))
              .status();
        }

        size_t sapi_internal_get_context_binding_size(const void* context,
                                                      absl::string_view name) {
          if (context == nullptr) return 0;
          absl::MutexLock sapi_lock(sapi_internal_context_binding_mutex);
          auto sapi_it = sapi_internal_context_binding_prim_map.find(
              {context, std::string(name)});
          CHECK(sapi_it != sapi_internal_context_binding_prim_map.end());
          return sapi_it->second;
        }

        size_t sapi_internal_get_context_binding_size_locked(
            const void* context, absl::string_view name)
            ABSL_EXCLUSIVE_LOCKS_REQUIRED(sapi_internal_context_binding_mutex) {
          if (context == nullptr) return 0;
          auto sapi_it = sapi_internal_context_binding_prim_map.find(
              {context, std::string(name)});
          CHECK(sapi_it != sapi_internal_context_binding_prim_map.end());
          return sapi_it->second;
        }
      )cc");
  return out;
}

void SandboxedLibraryEmitter::EmitFuncDecl(std::string& out, const Func& func) {
  std::string ret = "void";
  if (func.ret) {
    ret = func.ret->EmitRetType();
  }
  absl::StrAppend(&out,
                  absl::Substitute("extern \"C\" $0 $1(", ret, func.name));
  for (const auto& arg : func.args) {
    if (&arg != &func.args[0]) {
      absl::StrAppend(&out, ", ");
    }
    absl::StrAppend(&out, arg->EmitHostParams());
  }
  absl::StrAppend(&out, ")");
}

void SandboxedLibraryEmitter::EmitWrapperDecl(std::string& out,
                                              const Func& func) {
  // Strictly speaking, used/retain attributes are not needed here,
  // but they are required now to work around broken global sapi_library mode
  // (when functions attribute is empty).
  absl::StrAppend(
      &out,
      absl::Substitute("extern \"C\" __attribute__((used, retain)) void $0$1(",
                       kWrapperPrefix, func.name));
  for (const auto& arg : func.args) {
    if (&arg != &func.args[0]) {
      absl::StrAppend(&out, ", ");
    }
    absl::StrAppend(&out, arg->EmitSandboxeeParams());
  }
  if (func.ret) {
    if (!func.args.empty()) {
      absl::StrAppend(&out, ", ");
    }
    absl::StrAppend(&out, func.ret->EmitRetParams());
  }
  absl::StrAppend(&out, ")");
}

absl::StatusOr<std::string> SandboxedLibraryEmitter::Finalize(
    const std::string& body, bool is_header, bool add_includes) const {
  std::string out;
  if (is_header) {
    out.append(kHeaderHeader.data(), kHeaderHeader.size());
  }
  out.append(kCommonHeader.data(), kCommonHeader.size());
  if (add_includes) {
    std::vector<std::string> includes(includes_.begin(), includes_.end());
    std::sort(includes.begin(), includes.end());
    for (const auto& inc : includes) {
      // inc s already formatted as `#include <foo>` or `#include "foo"`.
      absl::StrAppendFormat(&out, "#include %s\n", inc);
    }
  }
  absl::StrAppend(&out, "\n", body, kCommonFooter);
  return ReformatGoogleStyle("input", out);
}


}  // namespace sapi
