// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Simple utility to wrap a binary file in a C++ source file.

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <utility>
#include <vector>

#include "absl/strings/ascii.h"
#include "absl/strings/match.h"
#include "absl/strings/str_cat.h"
#include "absl/strings/str_format.h"
#include "absl/strings/str_replace.h"
#include "absl/strings/string_view.h"
#include "sandboxed_api/util/fileops.h"
#include "sandboxed_api/util/raw_logging.h"

// C-escapes a character and writes it to a file stream.
void FWriteCEscapedC(int c, FILE* out) {
  /* clang-format off */
  constexpr char kCEscapedLen[256] = {
      4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 2, 4, 4, 2, 4, 4,  // \t, \n, \r
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  // "
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,  // '0'..'9'
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  // 'A'..'O'
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,  // 'P'..'Z', '\'
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  // 'a'..'o'
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4,  // 'p'..'z', DEL
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
      4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
  };
  /* clang-format on */

  int char_len = kCEscapedLen[c];
  if (char_len == 1) {
    fputc(c, out);
  } else if (char_len == 2) {
    fputc('\\', out);
    switch (c) {
      case '\0':
        fputc('0', out);
        break;
      case '\n':
        fputc('n', out);
        break;
      case '\r':
        fputc('r', out);
        break;
      case '\t':
        fputc('t', out);
        break;
      case '\"':
      case '\'':
      case '\\':
      case '?':
        fputc(c, out);
        break;
    }
  } else {
    fputc('\\', out);
    fputc('0' + c / 64, out);
    fputc('0' + (c % 64) / 8, out);
    fputc('0' + c % 8, out);
  }
}

// Small RAII class that wraps C-style FILE streams and sets up buffering.
class File {
 public:
  File(const char* name, const char* mode)
      : name_{name}, stream_{fopen(name, mode)}, buf_(4096, '\0') {
    SAPI_RAW_PCHECK(stream_ != nullptr, "Open %s", name_);
    std::setvbuf(stream_, &buf_[0], _IOFBF, buf_.size());
    Check();
  }
  ~File() { fclose(stream_); }

  void Check() {
    if (ferror(stream_)) {
      SAPI_RAW_PLOG(ERROR, "I/O on %s", name_);
      _Exit(EXIT_FAILURE);
    }
  }

  FILE* get() const { return stream_; }

 private:
  const char* name_;
  FILE* stream_;
  std::string buf_;
};

struct FileEntry {
  std::string in_filename;
  std::string basename;
  std::string ident;
};

// Format literals for generating the .h file
constexpr const char kHFileHeaderFmt[] =
    R"(// Automatically generated by sapi_cc_embed_data() build rule

#ifndef %1$s
#define %1$s

#include <cstddef>

#include "sandboxed_api/embed_toc.h"

)";
constexpr const char kHNamespaceBeginFmt[] =
    R"(namespace %s {
)";
constexpr const char kHFileTocDefsFmt[] =
    R"(
const ::sapi::EmbedToc* %1$s_create();
size_t %1$s_size();
)";
constexpr const char kHNamespaceEndFmt[] =
    R"(
}  // namespace %s
)";
constexpr const char kHFileFooterFmt[] =
    R"(
#endif  // %s
)";

// Format literals for generating the .cc file out of the input files.
constexpr const char kCcFileHeaderFmt[] =
    R"(// Automatically generated by sapi_cc_embed_data() build rule

#include "%s.h"

#include "sandboxed_api/embed_toc.h"

)";
constexpr const char kCcNamespaceBeginFmt[] =
    R"(namespace %s {

)";
constexpr const char kCcDataBeginFmt[] =
    R"(constexpr absl::string_view %s = {")";
constexpr const char kCcDataEndFmt[] =
    R"(", %d};
)";
constexpr const char kCcFileTocDefsBegin[] =
    R"(
constexpr ::sapi::EmbedToc kToc[] = {
)";
constexpr const char kCcFileTocDefsEntryFmt[] =
    R"(    {"%1$s", %2$s, ""},
)";
// Declaration of the dummy symbol defined in .text in the companion .S
// assembly file. Taking its address via asm volatile with constraint "r" in
// <name>_create() forces the compiler to emit address-generation instructions,
// creating an external symbol reference in an allocable section (.text) that
// forces the linker to extract the .S object from static libraries (.a
// archives) and shared libraries (.so) without sanitizer ABI mangling (e.g.
// DFSan).
constexpr const char kCcFileTocDefsDeclFmt[] =
    R"(extern "C" const char %1$s_embed_bin_mark_used[];
)";
constexpr const char kCcFileTocDefsSectionEntryFmt[] =
    R"(    {"%1$s", "", ".sapi_embed_%2$s"},
)";
constexpr const char kCcFileTocDefsEndFmt[] =
    R"(
    // Terminate array
    {"", "", ""},
};

const ::sapi::EmbedToc* %1$s_create() {
%2$s  return kToc;
}

size_t %1$s_size() {
  return (sizeof(kToc) / sizeof(kToc[0])) - 1;
}
)";
constexpr const char kCcNamespaceEndFmt[] =
    R"(
}  // namespace %s
)";

// Format literals for generating the .S file.
constexpr const char kSFileHeaderFmt[] =
    R"(// Automatically generated by sapi_cc_embed_data() build rule
)";
// Generates:
// 1. %1$s_embed_bin_mark_used: A dummy symbol in .text.
//    Referenced by <name>_create() in the .cc file to force the linker to
//    pull this .S object out of static archives (.a).
// 2. .section .sapi_embed_%1$s, "R": Unmapped ELF section containing the
//    binary payload via .incbin.
//    - Omits SHF_ALLOC ("a") so the section is NOT mapped into virtual memory
//      or physical RAM at process startup.
//    - Specifies SHF_GNU_RETAIN ("R") so linkers running with --gc-sections do
//      not strip the unmapped section from the final executable / DSO.
constexpr const char kSSectionFmt[] =
    R"(
.section .text, "ax"
.global %1$s_embed_bin_mark_used
.type %1$s_embed_bin_mark_used, %%object
%1$s_embed_bin_mark_used:
#if defined(__x86_64__) || defined(__i386__) || defined(__aarch64__) || defined(__riscv)
    ret
#elif defined(__arm__) || defined(__thumb__)
    bx lr
#else
#error "Unsupported architecture for sapi_cc_embed_data"
#endif

.section .sapi_embed_%1$s, "R"
.balign 4096
.global %1$s_embed_bin_start
.global %1$s_embed_bin_end

%1$s_embed_bin_start:
.incbin "%2$s"
%1$s_embed_bin_end:
)";

void WriteHeaderFile(const char* out_h_path, absl::string_view package,
                     absl::string_view toc_ident, absl::string_view ns,
                     bool have_ns) {
  File out_h(out_h_path, "wb");
  std::string header_guard = absl::StrFormat("%s_%s_H_", package, toc_ident);
  std::replace_if(
      header_guard.begin(), header_guard.end(),
      [](char c) { return !absl::ascii_isalnum(c); }, '_');
  absl::FPrintF(out_h.get(), kHFileHeaderFmt, header_guard);
  if (have_ns) {
    absl::FPrintF(out_h.get(), kHNamespaceBeginFmt, ns);
  }
  absl::FPrintF(out_h.get(), kHFileTocDefsFmt, toc_ident);
  if (have_ns) {
    absl::FPrintF(out_h.get(), kHNamespaceEndFmt, ns);
  }
  absl::FPrintF(out_h.get(), kHFileFooterFmt, header_guard);
  out_h.Check();
}

void WriteAssemblyFile(const char* out_s_path,
                       const std::vector<FileEntry>& entries) {
  File out_s(out_s_path, "wb");
  absl::FPrintF(out_s.get(), kSFileHeaderFmt);
  for (const auto& entry : entries) {
    absl::FPrintF(out_s.get(), kSSectionFmt, entry.ident, entry.in_filename);
  }
  out_s.Check();
}

void WriteLegacyPayloads(FILE* out_cc, const std::vector<FileEntry>& entries) {
  for (const auto& entry : entries) {
    File in(entry.in_filename.c_str(), "rb");
    absl::FPrintF(out_cc, kCcDataBeginFmt, entry.ident);
    int c;
    while ((c = fgetc(in.get())) != EOF) {
      FWriteCEscapedC(c, out_cc);
    }
    in.Check();
    absl::FPrintF(out_cc, kCcDataEndFmt, ftell(in.get()));
  }
}

int main(int argc, char* argv[]) {
  if (argc < 7) {
    // We're not aiming for human usability here, as this tool is always run as
    // part of the build.
    absl::FPrintF(
        stderr,
        "%s PACKAGE NAME NAMESPACE OUTPUT_H OUTPUT_CC [OUTPUT_S] INPUT...\n",
        argv[0]);
    return EXIT_FAILURE;
  }
  char** arg = &argv[1];

  const char* package = *arg++;
  --argc;
  const char* name = *arg++;
  std::string toc_ident = absl::StrReplaceAll(name, {{"-", "_"}});
  --argc;

  const char* ns = *arg++;
  const bool have_ns = strlen(ns) > 0;
  --argc;

  const char* out_h_path = *arg++;
  --argc;
  const char* out_cc_path = *arg++;
  --argc;

  const char* out_s_path = nullptr;
  if (argc > 1 && (absl::EndsWith(*arg, ".S") || absl::EndsWith(*arg, ".s"))) {
    out_s_path = *arg++;
    --argc;
  }

  // 1. Write header file.
  WriteHeaderFile(out_h_path, package, toc_ident, ns, have_ns);

  // 2. Parse all input files into a unified entry list.
  std::vector<FileEntry> entries;
  entries.reserve(argc - 1);
  while (argc > 1) {
    const char* in_filename = *arg++;
    --argc;
    std::string basename = sapi::file_util::fileops::Basename(in_filename);
    std::string ident;
    if (out_s_path == nullptr) {
      ident = absl::StrCat("k", basename);
    } else if (!basename.empty() && absl::ascii_isdigit(basename[0])) {
      ident = absl::StrCat("_", basename);
    } else {
      ident = basename;
    }
    std::replace_if(
        ident.begin(), ident.end(),
        [](char c) { return !absl::ascii_isalnum(c); }, '_');
    entries.push_back({in_filename, std::move(basename), std::move(ident)});
  }

  // 3. Write companion .S assembly file if in assembly mode.
  if (out_s_path != nullptr) {
    WriteAssemblyFile(out_s_path, entries);
  }

  // 4. Write .cc source file.
  File out_cc(out_cc_path, "wb");
  std::string package_name = package;
  if (!package_name.empty()) {
    absl::StrAppend(&package_name, "/");
  }
  absl::StrAppend(&package_name, name);
  absl::FPrintF(out_cc.get(), kCcFileHeaderFmt, package_name);
  if (have_ns) {
    absl::FPrintF(out_cc.get(), kCcNamespaceBeginFmt, ns);
  }

  if (out_s_path != nullptr) {
    for (const auto& entry : entries) {
      absl::FPrintF(out_cc.get(), kCcFileTocDefsDeclFmt, entry.ident);
    }
  } else {
    WriteLegacyPayloads(out_cc.get(), entries);
  }

  absl::FPrintF(out_cc.get(), kCcFileTocDefsBegin);
  for (const auto& entry : entries) {
    if (out_s_path != nullptr) {
      absl::FPrintF(out_cc.get(), kCcFileTocDefsSectionEntryFmt, entry.basename,
                    entry.ident);
    } else {
      absl::FPrintF(out_cc.get(), kCcFileTocDefsEntryFmt, entry.basename,
                    entry.ident);
    }
  }

  std::string mark_calls;
  if (out_s_path != nullptr) {
    for (const auto& entry : entries) {
      absl::StrAppend(&mark_calls, "  asm volatile(\"\" : : \"r\"(",
                      entry.ident, "_embed_bin_mark_used));\n");
    }
  }

  absl::FPrintF(out_cc.get(), kCcFileTocDefsEndFmt, toc_ident, mark_calls);
  if (have_ns) {
    absl::FPrintF(out_cc.get(), kCcNamespaceEndFmt, ns);
  }
  out_cc.Check();

  return EXIT_SUCCESS;
}
